/// <mls fileReference="_102047_/l1/agendaClinica/layer_1_external/adapters/http/controllers/agenda_diaria.test.ts" enhancement="_blank"/>

// Monitor cases of this page backend, as data (skills/monitorTests.md). Generated by agentMaterializeL12.
export const pageTests = {
  "moduleName": "agendaClinica",
  "page": "agenda_diaria",
  "variant": "backend",
  "actor": "profissional",
  "cases": [
    {
      "id": "carregarAgendaDiaria.positive",
      "routine": "agendaClinica.agenda_diaria.carregarAgendaDiaria",
      "params": {
        "page": 1,
        "pageSize": 10
      },
      "expect": {
        "ok": true,
        "shape": "paginated",
        "itemsKey": "consultas.items"
      },
      "mutating": false
    },
    {
      "id": "carregarMaisConsultasDoDia.positive",
      "routine": "agendaClinica.agenda_diaria.carregarMaisConsultasDoDia",
      "params": {
        "page": 2,
        "pageSize": 10
      },
      "expect": {
        "ok": true,
        "shape": "paginated",
        "itemsKey": "consultas.items"
      },
      "mutating": false
    },
    {
      "id": "carregarConsultaSelecionada.positive",
      "routine": "agendaClinica.agenda_diaria.carregarConsultaSelecionada",
      "params": {
        "consultaId": "<seedRef>"
      },
      "paramFieldRefs": {
        "consultaId": "Consulta.id"
      },
      "expect": {
        "ok": true,
        "shape": "object"
      },
      "mutating": false
    },
    {
      "id": "registrarAtendimento.details.required",
      "routine": "agendaClinica.agenda_diaria.registrarAtendimento",
      "params": {
        "id": "<seedRef>",
        "version": "<seedRef>"
      },
      "paramFieldRefs": {
        "id": "Consulta.id",
        "version": "Consulta.version"
      },
      "expect": {
        "ok": false,
        "errorCode": "VALIDATION_ERROR"
      },
      "mutating": true
    },
    {
      "id": "registrarAtendimento.transicaoConsultaValida",
      "routine": "agendaClinica.agenda_diaria.registrarAtendimento",
      "params": {
        "id": "<seedSpare>",
        "version": "<seedSpare>",
        "details": {
          "attendanceNote": "Registro de atendimento para validar a transição."
        }
      },
      "paramFieldRefs": {
        "id": "Consulta.id",
        "version": "Consulta.version"
      },
      "expect": {
        "ok": false,
        "errorCode": "CONFLICT"
      },
      "mutating": true
    },
    {
      "id": "registrarAtendimento.positive",
      "routine": "agendaClinica.agenda_diaria.registrarAtendimento",
      "params": {
        "id": "<seedRef>",
        "version": "<seedRef>",
        "details": {
          "attendanceNote": "Atendimento realizado e registrado pelo profissional."
        }
      },
      "paramFieldRefs": {
        "id": "Consulta.id",
        "version": "Consulta.version"
      },
      "expect": {
        "ok": true,
        "shape": "object"
      },
      "mutating": true
    }
  ]
} as const;
