/// <mls fileReference="_102047_/l1/agendaClinica/layer_1_external/adapters/http/controllers/consultas.test.ts" enhancement="_blank"/>

// Monitor cases of this page backend, as data (skills/monitorTests.md). Generated by agentMaterializeL12.
export const pageTests = {
  "moduleName": "agendaClinica",
  "page": "consultas",
  "variant": "backend",
  "actor": "recepcionista",
  "cases": [
    {
      "id": "carregarAgenda.positive",
      "routine": "agendaClinica.consultas.carregarAgenda",
      "params": {
        "dataAgenda": "2026-10-07",
        "page": 1,
        "pageSize": 20
      },
      "expect": {
        "ok": true,
        "shape": "object"
      },
      "mutating": false
    },
    {
      "id": "filtrarAgenda.positive",
      "routine": "agendaClinica.consultas.filtrarAgenda",
      "params": {
        "dataAgenda": "2026-10-07",
        "status": "scheduled",
        "page": 1,
        "pageSize": 20
      },
      "expect": {
        "ok": true,
        "shape": "object"
      },
      "mutating": false
    },
    {
      "id": "carregarMaisAgenda.positive",
      "routine": "agendaClinica.consultas.carregarMaisAgenda",
      "params": {
        "dataAgenda": "2026-10-07",
        "page": 2,
        "pageSize": 20
      },
      "expect": {
        "ok": true,
        "shape": "object"
      },
      "mutating": false
    },
    {
      "id": "consultarConsultaSelecionada.positive",
      "routine": "agendaClinica.consultas.consultarConsultaSelecionada",
      "params": {
        "id": "<seedRef>"
      },
      "paramFieldRefs": {
        "id": "Consulta.id"
      },
      "expect": {
        "ok": true,
        "shape": "object"
      },
      "mutating": false
    },
    {
      "id": "localizarPacientesParaAgendamento.positive",
      "routine": "agendaClinica.consultas.localizarPacientesParaAgendamento",
      "params": {
        "termo": "",
        "page": 1,
        "pageSize": 20
      },
      "expect": {
        "ok": true,
        "shape": "object"
      },
      "mutating": false
    },
    {
      "id": "carregarMaisPacientesParaAgendamento.positive",
      "routine": "agendaClinica.consultas.carregarMaisPacientesParaAgendamento",
      "params": {
        "termo": "",
        "page": 2,
        "pageSize": 20
      },
      "expect": {
        "ok": true,
        "shape": "object"
      },
      "mutating": false
    },
    {
      "id": "localizarProfissionaisParaAgendamento.positive",
      "routine": "agendaClinica.consultas.localizarProfissionaisParaAgendamento",
      "params": {
        "termo": "",
        "page": 1,
        "pageSize": 20
      },
      "expect": {
        "ok": true,
        "shape": "object"
      },
      "mutating": false
    },
    {
      "id": "carregarMaisProfissionaisParaAgendamento.positive",
      "routine": "agendaClinica.consultas.carregarMaisProfissionaisParaAgendamento",
      "params": {
        "termo": "",
        "page": 2,
        "pageSize": 20
      },
      "expect": {
        "ok": true,
        "shape": "object"
      },
      "mutating": false
    },
    {
      "id": "agendarConsulta.positive",
      "routine": "agendaClinica.consultas.agendarConsulta",
      "params": {
        "pacienteId": "<seedSpare>",
        "profissionalId": "<seedSpare>",
        "scheduledAt": "2026-10-08T15:00:00.000Z",
        "dataAgenda": "2026-10-08",
        "page": 1,
        "pageSize": 20
      },
      "paramFieldRefs": {
        "pacienteId": "Paciente.id",
        "profissionalId": "Profissional.id"
      },
      "expect": {
        "ok": true,
        "shape": "object"
      },
      "mutating": true
    },
    {
      "id": "agendarConsulta.consultaSemConflito",
      "routine": "agendaClinica.consultas.agendarConsulta",
      "params": {
        "pacienteId": "<seedSpare>",
        "profissionalId": "<seedValue>",
        "scheduledAt": "<seedValue>",
        "dataAgenda": "2026-10-07",
        "page": 1,
        "pageSize": 20
      },
      "paramFieldRefs": {
        "pacienteId": "Paciente.id",
        "profissionalId": "Consulta.profissionalId",
        "scheduledAt": "Consulta.scheduledAt"
      },
      "expect": {
        "ok": false
      },
      "mutating": true
    },
    {
      "id": "confirmarConsulta.positive",
      "routine": "agendaClinica.consultas.confirmarConsulta",
      "params": {
        "id": "<seedRef>",
        "version": "<seedValue>",
        "dataAgenda": "2026-10-07",
        "page": 1,
        "pageSize": 20
      },
      "paramFieldRefs": {
        "id": "Consulta.id",
        "version": "Consulta.version"
      },
      "expect": {
        "ok": true,
        "shape": "object"
      },
      "mutating": true
    },
    {
      "id": "confirmarConsulta.transicaoConsultaValida",
      "routine": "agendaClinica.consultas.confirmarConsulta",
      "params": {
        "id": "<seedRef>",
        "version": "<seedValue>",
        "dataAgenda": "2026-10-07",
        "page": 1,
        "pageSize": 20
      },
      "paramFieldRefs": {
        "id": "Consulta.id",
        "version": "Consulta.version"
      },
      "expect": {
        "ok": false
      },
      "mutating": true
    },
    {
      "id": "registrarFalta.positive",
      "routine": "agendaClinica.consultas.registrarFalta",
      "params": {
        "id": "<seedRef>",
        "version": "<seedValue>",
        "dataAgenda": "2026-10-07",
        "page": 1,
        "pageSize": 20
      },
      "paramFieldRefs": {
        "id": "Consulta.id",
        "version": "Consulta.version"
      },
      "expect": {
        "ok": true,
        "shape": "object"
      },
      "mutating": true
    },
    {
      "id": "registrarFalta.transicaoConsultaValida",
      "routine": "agendaClinica.consultas.registrarFalta",
      "params": {
        "id": "<seedRef>",
        "version": "<seedValue>",
        "dataAgenda": "2026-10-07",
        "page": 1,
        "pageSize": 20
      },
      "paramFieldRefs": {
        "id": "Consulta.id",
        "version": "Consulta.version"
      },
      "expect": {
        "ok": false
      },
      "mutating": true
    }
  ]
} as const;
