/// <mls fileReference="_102047_/l1/agendaClinica/layer_1_external/adapters/http/controllers/pacientes.test.ts" enhancement="_blank"/>

// Monitor cases of this page backend, as data (skills/monitorTests.md). Generated by agentMaterializeL12.
export const pageTests = {
  "moduleName": "agendaClinica",
  "page": "pacientes",
  "variant": "backend",
  "actor": "recepcionista",
  "cases": [
    {
      "id": "agendaClinica.pacientes.loadPatients.initial",
      "routine": "agendaClinica.pacientes.loadPatients",
      "params": {
        "page": 1,
        "pageSize": 10
      },
      "expect": {
        "ok": true,
        "shape": "object"
      },
      "mutating": false
    },
    {
      "id": "agendaClinica.pacientes.searchPatients.byName",
      "routine": "agendaClinica.pacientes.searchPatients",
      "params": {
        "nameSearch": "Paciente",
        "page": 1,
        "pageSize": 10
      },
      "expect": {
        "ok": true,
        "shape": "object"
      },
      "mutating": false
    },
    {
      "id": "agendaClinica.pacientes.loadPatientDetail.selected",
      "routine": "agendaClinica.pacientes.loadPatientDetail",
      "params": {
        "patientId": "<seedRef>"
      },
      "paramFieldRefs": {
        "patientId": "Paciente.id"
      },
      "expect": {
        "ok": true,
        "shape": "object"
      },
      "mutating": false
    },
    {
      "id": "agendaClinica.pacientes.savePatient.create",
      "routine": "agendaClinica.pacientes.savePatient",
      "params": {
        "details": {
          "identification": {
            "name": "Paciente Monitor"
          }
        }
      },
      "expect": {
        "ok": true,
        "shape": "object"
      },
      "mutating": true
    },
    {
      "id": "agendaClinica.pacientes.savePatient.details.required",
      "routine": "agendaClinica.pacientes.savePatient",
      "params": {},
      "expect": {
        "ok": false,
        "errorCode": "VALIDATION_ERROR"
      },
      "mutating": true
    }
  ]
} as const;
