/// <mls fileReference="_102047_/l1/comandaRestaurante/layer_1_external/adapters/http/controllers/atendimento.test.ts" enhancement="_blank"/>

// Monitor cases of this page backend, as data (skills/monitorTests.md). Generated by agentMaterializeL12.
export const pageTests = {
  "moduleName": "comandaRestaurante",
  "page": "atendimento",
  "variant": "backend",
  "actor": "garcom",
  "cases": [
    {
      "id": "carregarAtendimento.positive",
      "routine": "comandaRestaurante.atendimento.carregarAtendimento",
      "params": {
        "page": 1,
        "pageSize": 10
      },
      "expect": {
        "ok": true,
        "shape": "object"
      },
      "mutating": false
    },
    {
      "id": "atualizarLocalizacaoAtendimento.positive",
      "routine": "comandaRestaurante.atendimento.atualizarLocalizacaoAtendimento",
      "params": {
        "page": 1,
        "pageSize": 10
      },
      "expect": {
        "ok": true,
        "shape": "object"
      },
      "mutating": false
    },
    {
      "id": "obterComandaAtendimento.positive",
      "routine": "comandaRestaurante.atendimento.obterComandaAtendimento",
      "params": {
        "comandaId": "<seedRef>"
      },
      "paramFieldRefs": {
        "comandaId": "Comanda.id"
      },
      "expect": {
        "ok": true,
        "shape": "object"
      },
      "mutating": false
    },
    {
      "id": "carregarAtendimento.page.required",
      "routine": "comandaRestaurante.atendimento.carregarAtendimento",
      "params": {
        "pageSize": 10
      },
      "expect": {
        "ok": false,
        "errorCode": "VALIDATION_ERROR"
      },
      "mutating": false
    },
    {
      "id": "carregarAtendimento.pageSize.required",
      "routine": "comandaRestaurante.atendimento.carregarAtendimento",
      "params": {
        "page": 1
      },
      "expect": {
        "ok": false,
        "errorCode": "VALIDATION_ERROR"
      },
      "mutating": false
    },
    {
      "id": "atualizarLocalizacaoAtendimento.page.required",
      "routine": "comandaRestaurante.atendimento.atualizarLocalizacaoAtendimento",
      "params": {
        "pageSize": 10
      },
      "expect": {
        "ok": false,
        "errorCode": "VALIDATION_ERROR"
      },
      "mutating": false
    },
    {
      "id": "atualizarLocalizacaoAtendimento.pageSize.required",
      "routine": "comandaRestaurante.atendimento.atualizarLocalizacaoAtendimento",
      "params": {
        "page": 1
      },
      "expect": {
        "ok": false,
        "errorCode": "VALIDATION_ERROR"
      },
      "mutating": false
    },
    {
      "id": "obterComandaAtendimento.comandaId.required",
      "routine": "comandaRestaurante.atendimento.obterComandaAtendimento",
      "params": {},
      "expect": {
        "ok": false,
        "errorCode": "VALIDATION_ERROR"
      },
      "mutating": false
    },
    {
      "id": "abrirComanda.mesaId.required",
      "routine": "comandaRestaurante.atendimento.abrirComanda",
      "params": {},
      "expect": {
        "ok": false,
        "errorCode": "VALIDATION_ERROR"
      },
      "mutating": true
    },
    {
      "id": "abrirComanda.mesaIndisponivel.conflict",
      "routine": "comandaRestaurante.atendimento.abrirComanda",
      "params": {
        "mesaId": "<seedRef>"
      },
      "paramFieldRefs": {
        "mesaId": "Mesa.id"
      },
      "expect": {
        "ok": false,
        "errorCode": "CONFLICT"
      },
      "mutating": true
    },
    {
      "id": "abrirComanda.positive",
      "routine": "comandaRestaurante.atendimento.abrirComanda",
      "params": {
        "mesaId": "<seedSpare>"
      },
      "paramFieldRefs": {
        "mesaId": "Mesa.id"
      },
      "expect": {
        "ok": true,
        "shape": "object"
      },
      "mutating": true
    },
    {
      "id": "abrirComanda.umaComandaAbertaPorMesa.conflict",
      "routine": "comandaRestaurante.atendimento.abrirComanda",
      "params": {
        "mesaId": "<seedSpare>"
      },
      "paramFieldRefs": {
        "mesaId": "Mesa.id"
      },
      "expect": {
        "ok": false,
        "errorCode": "CONFLICT"
      },
      "mutating": true
    },
    {
      "id": "lancarItem.comandaId.required",
      "routine": "comandaRestaurante.atendimento.lancarItem",
      "params": {
        "itemCardapioId": "<seedRef>",
        "details": {
          "quantidade": 1
        }
      },
      "paramFieldRefs": {
        "itemCardapioId": "ItemCardapio.id"
      },
      "expect": {
        "ok": false,
        "errorCode": "VALIDATION_ERROR"
      },
      "mutating": true
    },
    {
      "id": "lancarItem.itemCardapioId.required",
      "routine": "comandaRestaurante.atendimento.lancarItem",
      "params": {
        "comandaId": "<seedRef>",
        "details": {
          "quantidade": 1
        }
      },
      "paramFieldRefs": {
        "comandaId": "Comanda.id"
      },
      "expect": {
        "ok": false,
        "errorCode": "VALIDATION_ERROR"
      },
      "mutating": true
    },
    {
      "id": "lancarItem.comandaFechada.conflict",
      "routine": "comandaRestaurante.atendimento.lancarItem",
      "params": {
        "comandaId": "<seedRef>",
        "itemCardapioId": "<seedRef>",
        "details": {
          "quantidade": 1
        }
      },
      "paramFieldRefs": {
        "comandaId": "Comanda.id",
        "itemCardapioId": "ItemCardapio.id"
      },
      "expect": {
        "ok": false,
        "errorCode": "CONFLICT"
      },
      "mutating": true
    },
    {
      "id": "lancarItem.positive",
      "routine": "comandaRestaurante.atendimento.lancarItem",
      "params": {
        "comandaId": "<seedRef>",
        "itemCardapioId": "<seedRef>",
        "details": {
          "quantidade": 2,
          "observacao": "Sem cebola"
        }
      },
      "paramFieldRefs": {
        "comandaId": "Comanda.id",
        "itemCardapioId": "ItemCardapio.id"
      },
      "expect": {
        "ok": true,
        "shape": "object"
      },
      "mutating": true
    },
    {
      "id": "cancelarItem.id.required",
      "routine": "comandaRestaurante.atendimento.cancelarItem",
      "params": {
        "version": "<seedRef>"
      },
      "paramFieldRefs": {
        "version": "ItemComanda.version"
      },
      "expect": {
        "ok": false,
        "errorCode": "VALIDATION_ERROR"
      },
      "mutating": true
    },
    {
      "id": "cancelarItem.version.required",
      "routine": "comandaRestaurante.atendimento.cancelarItem",
      "params": {
        "id": "<seedRef>"
      },
      "paramFieldRefs": {
        "id": "ItemComanda.id"
      },
      "expect": {
        "ok": false,
        "errorCode": "VALIDATION_ERROR"
      },
      "mutating": true
    },
    {
      "id": "cancelarItem.itemNaoLancado.conflict",
      "routine": "comandaRestaurante.atendimento.cancelarItem",
      "params": {
        "id": "<seedRef>",
        "version": "<seedRef>"
      },
      "paramFieldRefs": {
        "id": "ItemComanda.id",
        "version": "ItemComanda.version"
      },
      "expect": {
        "ok": false,
        "errorCode": "CONFLICT"
      },
      "mutating": true
    },
    {
      "id": "cancelarItem.positive",
      "routine": "comandaRestaurante.atendimento.cancelarItem",
      "params": {
        "id": "<seedSpare>",
        "version": "<seedSpare>"
      },
      "paramFieldRefs": {
        "id": "ItemComanda.id",
        "version": "ItemComanda.version"
      },
      "expect": {
        "ok": true,
        "shape": "object"
      },
      "mutating": true
    }
  ]
} as const;
