/// <mls fileReference="_102047_/l1/comandaRestaurante/layer_1_external/adapters/http/controllers/cardapio.test.ts" enhancement="_blank"/>

// Monitor cases of this page backend, as data (skills/monitorTests.md). Generated by agentMaterializeL12.
export const pageTests = {
  "moduleName": "comandaRestaurante",
  "page": "cardapio",
  "variant": "backend",
  "actor": "caixa",
  "cases": [
    {
      "id": "carregarItensCardapio.positive",
      "routine": "comandaRestaurante.cardapio.carregarItensCardapio",
      "params": {
        "page": 1,
        "pageSize": 1
      },
      "expect": {
        "ok": true,
        "shape": "object"
      },
      "mutating": false
    },
    {
      "id": "carregarMaisItensCardapio.positive",
      "routine": "comandaRestaurante.cardapio.carregarMaisItensCardapio",
      "params": {
        "page": 2,
        "pageSize": 1
      },
      "expect": {
        "ok": true,
        "shape": "object"
      },
      "mutating": false
    },
    {
      "id": "obterItemCardapio.positive",
      "routine": "comandaRestaurante.cardapio.obterItemCardapio",
      "params": {
        "id": "<seedRef>"
      },
      "paramFieldRefs": {
        "id": "ItemCardapio.id"
      },
      "expect": {
        "ok": true,
        "shape": "object"
      },
      "mutating": false
    },
    {
      "id": "cadastrarItemCardapio.persisted",
      "routine": "comandaRestaurante.cardapio.carregarItensCardapio",
      "params": {
        "page": 1,
        "pageSize": 100
      },
      "expect": {
        "ok": true,
        "shape": "object"
      },
      "mutating": false
    },
    {
      "id": "atualizarItemCardapio.persisted",
      "routine": "comandaRestaurante.cardapio.obterItemCardapio",
      "params": {
        "id": "<seedRef>"
      },
      "paramFieldRefs": {
        "id": "ItemCardapio.id"
      },
      "expect": {
        "ok": true,
        "shape": "object"
      },
      "mutating": false
    },
    {
      "id": "obterItemCardapio.id.required",
      "routine": "comandaRestaurante.cardapio.obterItemCardapio",
      "params": {},
      "expect": {
        "ok": false,
        "errorCode": "VALIDATION_ERROR"
      },
      "mutating": false
    },
    {
      "id": "cadastrarItemCardapio.positive",
      "routine": "comandaRestaurante.cardapio.cadastrarItemCardapio",
      "params": {
        "name": "Item monitor cardápio",
        "details": {
          "precoVigente": "19.90"
        }
      },
      "expect": {
        "ok": true,
        "shape": "object"
      },
      "mutating": true
    },
    {
      "id": "cadastrarItemCardapio.name.required",
      "routine": "comandaRestaurante.cardapio.cadastrarItemCardapio",
      "params": {
        "details": {
          "precoVigente": "19.90"
        }
      },
      "expect": {
        "ok": false,
        "errorCode": "VALIDATION_ERROR"
      },
      "mutating": true
    },
    {
      "id": "cadastrarItemCardapio.details.required",
      "routine": "comandaRestaurante.cardapio.cadastrarItemCardapio",
      "params": {
        "name": "Item sem detalhes"
      },
      "expect": {
        "ok": false,
        "errorCode": "VALIDATION_ERROR"
      },
      "mutating": true
    },
    {
      "id": "atualizarItemCardapio.positive",
      "routine": "comandaRestaurante.cardapio.atualizarItemCardapio",
      "params": {
        "id": "<seedRef>",
        "version": "<seedValue>",
        "name": "Item monitor atualizado",
        "details": {
          "precoVigente": "24.90"
        }
      },
      "paramFieldRefs": {
        "id": "ItemCardapio.id",
        "version": "ItemCardapio.version"
      },
      "expect": {
        "ok": true,
        "shape": "object"
      },
      "mutating": true
    },
    {
      "id": "atualizarItemCardapio.id.required",
      "routine": "comandaRestaurante.cardapio.atualizarItemCardapio",
      "params": {
        "version": "<seedValue>",
        "name": "Item atualizado",
        "details": {
          "precoVigente": "24.90"
        }
      },
      "paramFieldRefs": {
        "version": "ItemCardapio.version"
      },
      "expect": {
        "ok": false,
        "errorCode": "VALIDATION_ERROR"
      },
      "mutating": true
    },
    {
      "id": "atualizarItemCardapio.version.required",
      "routine": "comandaRestaurante.cardapio.atualizarItemCardapio",
      "params": {
        "id": "<seedRef>",
        "name": "Item atualizado",
        "details": {
          "precoVigente": "24.90"
        }
      },
      "paramFieldRefs": {
        "id": "ItemCardapio.id"
      },
      "expect": {
        "ok": false,
        "errorCode": "VALIDATION_ERROR"
      },
      "mutating": true
    },
    {
      "id": "atualizarItemCardapio.name.required",
      "routine": "comandaRestaurante.cardapio.atualizarItemCardapio",
      "params": {
        "id": "<seedRef>",
        "version": "<seedValue>",
        "details": {
          "precoVigente": "24.90"
        }
      },
      "paramFieldRefs": {
        "id": "ItemCardapio.id",
        "version": "ItemCardapio.version"
      },
      "expect": {
        "ok": false,
        "errorCode": "VALIDATION_ERROR"
      },
      "mutating": true
    },
    {
      "id": "atualizarItemCardapio.details.required",
      "routine": "comandaRestaurante.cardapio.atualizarItemCardapio",
      "params": {
        "id": "<seedRef>",
        "version": "<seedValue>",
        "name": "Item sem detalhes"
      },
      "paramFieldRefs": {
        "id": "ItemCardapio.id",
        "version": "ItemCardapio.version"
      },
      "expect": {
        "ok": false,
        "errorCode": "VALIDATION_ERROR"
      },
      "mutating": true
    }
  ]
} as const;
