/// <mls fileReference="_102047_/l1/comandaRestaurante/layer_1_external/adapters/http/controllers/fechamento.test.ts" enhancement="_blank"/>

// Monitor cases of this page backend, as data (skills/monitorTests.md). Generated by agentMaterializeL12.
export const pageTests = {
  "moduleName": "comandaRestaurante",
  "page": "fechamento",
  "variant": "backend",
  "actor": "caixa",
  "cases": [
    {
      "id": "carregarFechamento.positive",
      "routine": "comandaRestaurante.fechamento.carregarFechamento",
      "params": {
        "page": 1,
        "pageSize": 10
      },
      "expect": {
        "ok": true,
        "shape": "object"
      },
      "mutating": false
    },
    {
      "id": "buscarComandasAbertas.positive",
      "routine": "comandaRestaurante.fechamento.buscarComandasAbertas",
      "params": {
        "page": 1,
        "pageSize": 10
      },
      "expect": {
        "ok": true,
        "shape": "object"
      },
      "mutating": false
    },
    {
      "id": "carregarMaisComandasAbertas.positive",
      "routine": "comandaRestaurante.fechamento.carregarMaisComandasAbertas",
      "params": {
        "page": 2,
        "pageSize": 1
      },
      "expect": {
        "ok": true,
        "shape": "object"
      },
      "mutating": false
    },
    {
      "id": "obterComandaParaFechamento.positive",
      "routine": "comandaRestaurante.fechamento.obterComandaParaFechamento",
      "params": {
        "id": "<seedRef>"
      },
      "paramFieldRefs": {
        "id": "Comanda.id"
      },
      "expect": {
        "ok": true,
        "shape": "object"
      },
      "mutating": false
    },
    {
      "id": "carregarFechamento.page.required",
      "routine": "comandaRestaurante.fechamento.carregarFechamento",
      "params": {
        "pageSize": 10
      },
      "expect": {
        "ok": false,
        "errorCode": "VALIDATION_ERROR"
      },
      "mutating": false
    },
    {
      "id": "carregarFechamento.pageSize.required",
      "routine": "comandaRestaurante.fechamento.carregarFechamento",
      "params": {
        "page": 1
      },
      "expect": {
        "ok": false,
        "errorCode": "VALIDATION_ERROR"
      },
      "mutating": false
    },
    {
      "id": "buscarComandasAbertas.page.required",
      "routine": "comandaRestaurante.fechamento.buscarComandasAbertas",
      "params": {
        "pageSize": 10
      },
      "expect": {
        "ok": false,
        "errorCode": "VALIDATION_ERROR"
      },
      "mutating": false
    },
    {
      "id": "buscarComandasAbertas.pageSize.required",
      "routine": "comandaRestaurante.fechamento.buscarComandasAbertas",
      "params": {
        "page": 1
      },
      "expect": {
        "ok": false,
        "errorCode": "VALIDATION_ERROR"
      },
      "mutating": false
    },
    {
      "id": "carregarMaisComandasAbertas.page.required",
      "routine": "comandaRestaurante.fechamento.carregarMaisComandasAbertas",
      "params": {
        "pageSize": 1
      },
      "expect": {
        "ok": false,
        "errorCode": "VALIDATION_ERROR"
      },
      "mutating": false
    },
    {
      "id": "carregarMaisComandasAbertas.pageSize.required",
      "routine": "comandaRestaurante.fechamento.carregarMaisComandasAbertas",
      "params": {
        "page": 2
      },
      "expect": {
        "ok": false,
        "errorCode": "VALIDATION_ERROR"
      },
      "mutating": false
    },
    {
      "id": "obterComandaParaFechamento.id.required",
      "routine": "comandaRestaurante.fechamento.obterComandaParaFechamento",
      "params": {},
      "expect": {
        "ok": false,
        "errorCode": "VALIDATION_ERROR"
      },
      "mutating": false
    },
    {
      "id": "fecharComandaPaga.pagamentoObrigatorioNoFechamento",
      "routine": "comandaRestaurante.fechamento.fecharComandaPaga",
      "params": {
        "id": "<seedSpare>",
        "version": "<seedSpare>",
        "details": {}
      },
      "paramFieldRefs": {
        "id": "Comanda.id",
        "version": "Comanda.version"
      },
      "expect": {
        "ok": false,
        "errorCode": "VALIDATION_ERROR"
      },
      "mutating": true
    },
    {
      "id": "fecharComandaPaga.descontoExcedeSubtotal",
      "routine": "comandaRestaurante.fechamento.fecharComandaPaga",
      "params": {
        "id": "<seedSpare>",
        "version": "<seedSpare>",
        "details": {
          "discountAmount": "999999999.99",
          "paymentMethod": "cash"
        }
      },
      "paramFieldRefs": {
        "id": "Comanda.id",
        "version": "Comanda.version"
      },
      "expect": {
        "ok": false,
        "errorCode": "VALIDATION_ERROR"
      },
      "mutating": true
    },
    {
      "id": "fecharComandaPaga.positive",
      "routine": "comandaRestaurante.fechamento.fecharComandaPaga",
      "params": {
        "id": "<seedRef>",
        "version": "<seedRef>",
        "details": {
          "paymentMethod": "pix"
        }
      },
      "paramFieldRefs": {
        "id": "Comanda.id",
        "version": "Comanda.version"
      },
      "expect": {
        "ok": true,
        "shape": "object"
      },
      "mutating": true
    }
  ]
} as const;
