/// <mls fileReference="_102047_/l1/comandaRestaurante/layer_1_external/adapters/http/controllers/inicio.test.ts" enhancement="_blank"/>

// Monitor cases of this page backend, as data (skills/monitorTests.md). Generated by agentMaterializeL12.
export const pageTests = {
  "moduleName": "comandaRestaurante",
  "page": "inicio",
  "variant": "backend",
  "actor": "caixa",
  "cases": [
    {
      "id": "comandaRestaurante.inicio.carregarResumoOperacional.positive",
      "routine": "comandaRestaurante.inicio.carregarResumoOperacional",
      "params": {},
      "expect": {
        "ok": true,
        "shape": "object"
      },
      "mutating": false
    }
  ]
} as const;
