/// <mls fileReference="_102047_/l1/comandaRestaurante/layer_1_external/adapters/http/controllers/mesas.test.ts" enhancement="_blank"/>

// Monitor cases of this page backend, as data (skills/monitorTests.md). Generated by agentMaterializeL12.
export const pageTests = {
  "moduleName": "comandaRestaurante",
  "page": "mesas",
  "variant": "backend",
  "actor": "caixa",
  "cases": [
    {
      "id": "comandaRestaurante.mesas.carregarMesas.ok",
      "routine": "comandaRestaurante.mesas.carregarMesas",
      "params": {},
      "expect": {
        "ok": true,
        "shape": "object"
      },
      "mutating": false
    },
    {
      "id": "comandaRestaurante.mesas.criarMesa.ok",
      "routine": "comandaRestaurante.mesas.criarMesa",
      "params": {
        "code": "MESA-MONITOR-NOVA"
      },
      "expect": {
        "ok": true,
        "shape": "object"
      },
      "mutating": true
    },
    {
      "id": "comandaRestaurante.mesas.criarMesa.code.required",
      "routine": "comandaRestaurante.mesas.criarMesa",
      "params": {},
      "expect": {
        "ok": false,
        "errorCode": "VALIDATION_ERROR"
      },
      "mutating": true
    },
    {
      "id": "comandaRestaurante.mesas.atualizarMesa.ok",
      "routine": "comandaRestaurante.mesas.atualizarMesa",
      "params": {
        "id": "<seedRef>",
        "version": "<seedValue>",
        "code": "MESA-MONITOR-ATUALIZADA"
      },
      "paramFieldRefs": {
        "id": "Mesa.id",
        "version": "Mesa.version"
      },
      "expect": {
        "ok": true,
        "shape": "object"
      },
      "mutating": true
    },
    {
      "id": "comandaRestaurante.mesas.atualizarMesa.id.required",
      "routine": "comandaRestaurante.mesas.atualizarMesa",
      "params": {
        "version": "<seedValue>",
        "code": "MESA-MONITOR-SEM-ID"
      },
      "paramFieldRefs": {
        "version": "Mesa.version"
      },
      "expect": {
        "ok": false,
        "errorCode": "VALIDATION_ERROR"
      },
      "mutating": true
    },
    {
      "id": "comandaRestaurante.mesas.atualizarMesa.version.required",
      "routine": "comandaRestaurante.mesas.atualizarMesa",
      "params": {
        "id": "<seedRef>",
        "code": "MESA-MONITOR-SEM-VERSAO"
      },
      "paramFieldRefs": {
        "id": "Mesa.id"
      },
      "expect": {
        "ok": false,
        "errorCode": "VALIDATION_ERROR"
      },
      "mutating": true
    },
    {
      "id": "comandaRestaurante.mesas.atualizarMesa.code.required",
      "routine": "comandaRestaurante.mesas.atualizarMesa",
      "params": {
        "id": "<seedRef>",
        "version": "<seedValue>"
      },
      "paramFieldRefs": {
        "id": "Mesa.id",
        "version": "Mesa.version"
      },
      "expect": {
        "ok": false,
        "errorCode": "VALIDATION_ERROR"
      },
      "mutating": true
    }
  ]
} as const;
