/// <mls fileReference="_102047_/l2/agendaClinica/web/shared/consultas.test.ts" enhancement="_102020_/l2/enhancementAura"/>

import type { AgendaClinicaConsultasBase } from '/_102047_/l2/agendaClinica/web/shared/consultas.js';

type IsAny<T> = 0 extends (1 & T) ? true : false;
type Assignable<Actual, Expected> = IsAny<Actual> extends true ? false : [Actual] extends [Expected] ? true : false;
type Assert<T extends true> = T;

declare const page: AgendaClinicaConsultasBase;

// This file is generated from .defs.ts. Add narrower state/action assertions here as materialization rules evolve.
type _State_pageStatus = Assert<Assignable<typeof page.pageStatus, "idle" | "loading" | "empty" | "success" | "error">>;
type _State_scenary = Assert<Assignable<typeof page.scenary, "base" | "detailConsulta" | "createConsulta" | "updateConsulta">>;
type _State_pacienteId = Assert<Assignable<typeof page.pacienteId, unknown>>;
type _State_profissionalId = Assert<Assignable<typeof page.profissionalId, unknown>>;
type _State_scheduledAt = Assert<Assignable<typeof page.scheduledAt, unknown>>;
type _State_confirmedAt = Assert<Assignable<typeof page.confirmedAt, unknown>>;
type _State_createConsultaStatus = Assert<Assignable<typeof page.createConsultaStatus, "idle" | "loading" | "success" | "error">>;
type _State_createConsultaError = Assert<Assignable<typeof page.createConsultaError, unknown>>;
type _State_createConsultaResult = Assert<Assignable<typeof page.createConsultaResult, unknown>>;
type _State_id = Assert<Assignable<typeof page.id, unknown>>;
type _State_registrarFaltaStatus = Assert<Assignable<typeof page.registrarFaltaStatus, "idle" | "loading" | "success" | "error">>;
type _State_registrarFaltaError = Assert<Assignable<typeof page.registrarFaltaError, unknown>>;
type _State_registrarFaltaResult = Assert<Assignable<typeof page.registrarFaltaResult, unknown>>;
type _State_id = Assert<Assignable<typeof page.id, unknown>>;
type _State_pacienteId = Assert<Assignable<typeof page.pacienteId, unknown>>;
type _State_profissionalId = Assert<Assignable<typeof page.profissionalId, unknown>>;
type _State_scheduledAt = Assert<Assignable<typeof page.scheduledAt, unknown>>;
type _State_confirmedAt = Assert<Assignable<typeof page.confirmedAt, unknown>>;
type _State_updateConsultaStatus = Assert<Assignable<typeof page.updateConsultaStatus, "idle" | "loading" | "success" | "error">>;
type _State_updateConsultaError = Assert<Assignable<typeof page.updateConsultaError, unknown>>;
type _State_updateConsultaResult = Assert<Assignable<typeof page.updateConsultaResult, unknown>>;
type _State_id = Assert<Assignable<typeof page.id, unknown>>;
type _State_pacienteId = Assert<Assignable<typeof page.pacienteId, unknown>>;
type _State_profissionalId = Assert<Assignable<typeof page.profissionalId, unknown>>;
type _State_scheduledAt = Assert<Assignable<typeof page.scheduledAt, unknown>>;
type _State_status = Assert<Assignable<typeof page.status, "scheduled" | "noShow" | "attended" | null>>;
type _State_page = Assert<Assignable<typeof page.page, unknown>>;
type _State_listConsultaStatus = Assert<Assignable<typeof page.listConsultaStatus, "idle" | "loading" | "success" | "error">>;
type _State_listConsultaError = Assert<Assignable<typeof page.listConsultaError, unknown>>;
type _State_listConsultaResult = Assert<Assignable<typeof page.listConsultaResult, unknown[]>>;
type _State_id = Assert<Assignable<typeof page.id, unknown>>;
type _State_subtype = Assert<Assignable<typeof page.subtype, "Person" | null>>;
type _State_name = Assert<Assignable<typeof page.name, unknown>>;
type _State_docType = Assert<Assignable<typeof page.docType, "CPF" | "NationalId" | "Passport" | "Other" | null>>;
type _State_docId = Assert<Assignable<typeof page.docId, unknown>>;
type _State_countryCode = Assert<Assignable<typeof page.countryCode, unknown>>;
type _State_page = Assert<Assignable<typeof page.page, unknown>>;
type _State_listPacienteStatus = Assert<Assignable<typeof page.listPacienteStatus, "idle" | "loading" | "success" | "error">>;
type _State_listPacienteError = Assert<Assignable<typeof page.listPacienteError, unknown>>;
type _State_listPacienteResult = Assert<Assignable<typeof page.listPacienteResult, unknown[]>>;
type _State_id = Assert<Assignable<typeof page.id, unknown>>;
type _State_subtype = Assert<Assignable<typeof page.subtype, "Person" | null>>;
type _State_name = Assert<Assignable<typeof page.name, unknown>>;
type _State_status = Assert<Assignable<typeof page.status, "Active" | "Inactive" | "Merged" | "Blocked" | null>>;
type _State_docType = Assert<Assignable<typeof page.docType, "CPF" | "Passport" | "NationalId" | "Other" | null>>;
type _State_docId = Assert<Assignable<typeof page.docId, unknown>>;
type _State_countryCode = Assert<Assignable<typeof page.countryCode, unknown>>;
type _State_page = Assert<Assignable<typeof page.page, unknown>>;
type _State_listProfissionalStatus = Assert<Assignable<typeof page.listProfissionalStatus, "idle" | "loading" | "success" | "error">>;
type _State_listProfissionalError = Assert<Assignable<typeof page.listProfissionalError, unknown>>;
type _State_listProfissionalResult = Assert<Assignable<typeof page.listProfissionalResult, unknown[]>>;
type _Action_setScenario = Assert<Assignable<typeof page.setScenario, (...args: any[]) => unknown>>;
type _Action_selectCreateConsultaPacienteId = Assert<Assignable<typeof page.selectCreateConsultaPacienteId, (...args: any[]) => unknown>>;
type _Action_selectCreateConsultaProfissionalId = Assert<Assignable<typeof page.selectCreateConsultaProfissionalId, (...args: any[]) => unknown>>;
type _Action_setCreateConsultaScheduledAt = Assert<Assignable<typeof page.setCreateConsultaScheduledAt, (...args: any[]) => unknown>>;
type _Action_setCreateConsultaDetailsTelephoneConfirmationConfirmedAt = Assert<Assignable<typeof page.setCreateConsultaDetailsTelephoneConfirmationConfirmedAt, (...args: any[]) => unknown>>;
type _Action_runCreateConsulta = Assert<Assignable<typeof page.runCreateConsulta, (...args: any[]) => unknown>>;
type _Action_selectRegistrarFaltaId = Assert<Assignable<typeof page.selectRegistrarFaltaId, (...args: any[]) => unknown>>;
type _Action_runRegistrarFalta = Assert<Assignable<typeof page.runRegistrarFalta, (...args: any[]) => unknown>>;
type _Action_selectUpdateConsultaId = Assert<Assignable<typeof page.selectUpdateConsultaId, (...args: any[]) => unknown>>;
type _Action_selectUpdateConsultaPacienteId = Assert<Assignable<typeof page.selectUpdateConsultaPacienteId, (...args: any[]) => unknown>>;
type _Action_selectUpdateConsultaProfissionalId = Assert<Assignable<typeof page.selectUpdateConsultaProfissionalId, (...args: any[]) => unknown>>;
type _Action_setUpdateConsultaScheduledAt = Assert<Assignable<typeof page.setUpdateConsultaScheduledAt, (...args: any[]) => unknown>>;
type _Action_setUpdateConsultaDetailsTelephoneConfirmationConfirmedAt = Assert<Assignable<typeof page.setUpdateConsultaDetailsTelephoneConfirmationConfirmedAt, (...args: any[]) => unknown>>;
type _Action_runUpdateConsulta = Assert<Assignable<typeof page.runUpdateConsulta, (...args: any[]) => unknown>>;
type _Action_setListConsultaId = Assert<Assignable<typeof page.setListConsultaId, (...args: any[]) => unknown>>;
type _Action_selectListConsultaPacienteId = Assert<Assignable<typeof page.selectListConsultaPacienteId, (...args: any[]) => unknown>>;
type _Action_selectListConsultaProfissionalId = Assert<Assignable<typeof page.selectListConsultaProfissionalId, (...args: any[]) => unknown>>;
type _Action_setListConsultaScheduledAt = Assert<Assignable<typeof page.setListConsultaScheduledAt, (...args: any[]) => unknown>>;
type _Action_setListConsultaStatus = Assert<Assignable<typeof page.setListConsultaStatus, (...args: any[]) => unknown>>;
type _Action_runListConsulta = Assert<Assignable<typeof page.runListConsulta, (...args: any[]) => unknown>>;
type _Action_setListPacienteId = Assert<Assignable<typeof page.setListPacienteId, (...args: any[]) => unknown>>;
type _Action_setListPacienteDetailsIdentificationSubtype = Assert<Assignable<typeof page.setListPacienteDetailsIdentificationSubtype, (...args: any[]) => unknown>>;
type _Action_setListPacienteDetailsIdentificationName = Assert<Assignable<typeof page.setListPacienteDetailsIdentificationName, (...args: any[]) => unknown>>;
type _Action_setListPacienteDetailsIdentificationDocType = Assert<Assignable<typeof page.setListPacienteDetailsIdentificationDocType, (...args: any[]) => unknown>>;
type _Action_setListPacienteDetailsIdentificationDocId = Assert<Assignable<typeof page.setListPacienteDetailsIdentificationDocId, (...args: any[]) => unknown>>;
type _Action_setListPacienteDetailsIdentificationCountryCode = Assert<Assignable<typeof page.setListPacienteDetailsIdentificationCountryCode, (...args: any[]) => unknown>>;
type _Action_runListPaciente = Assert<Assignable<typeof page.runListPaciente, (...args: any[]) => unknown>>;
type _Action_setListProfissionalId = Assert<Assignable<typeof page.setListProfissionalId, (...args: any[]) => unknown>>;
type _Action_setListProfissionalDetailsIdentificationSubtype = Assert<Assignable<typeof page.setListProfissionalDetailsIdentificationSubtype, (...args: any[]) => unknown>>;
type _Action_setListProfissionalDetailsIdentificationName = Assert<Assignable<typeof page.setListProfissionalDetailsIdentificationName, (...args: any[]) => unknown>>;
type _Action_setListProfissionalDetailsIdentificationStatus = Assert<Assignable<typeof page.setListProfissionalDetailsIdentificationStatus, (...args: any[]) => unknown>>;
type _Action_setListProfissionalDetailsIdentificationDocType = Assert<Assignable<typeof page.setListProfissionalDetailsIdentificationDocType, (...args: any[]) => unknown>>;
type _Action_setListProfissionalDetailsIdentificationDocId = Assert<Assignable<typeof page.setListProfissionalDetailsIdentificationDocId, (...args: any[]) => unknown>>;
type _Action_setListProfissionalDetailsIdentificationCountryCode = Assert<Assignable<typeof page.setListProfissionalDetailsIdentificationCountryCode, (...args: any[]) => unknown>>;
type _Action_runListProfissional = Assert<Assignable<typeof page.runListProfissional, (...args: any[]) => unknown>>;

export {};