/// <mls fileReference="_102047_/l2/agendaClinica/web/shared/consultas.ts" enhancement="_102020_/l2/enhancementAura"/>

import { property } from 'lit/decorators.js';
import { StateLitElement } from '/_102029_/l2/stateLitElement.js';
import { execBff } from '/_102029_/l2/bffClient.js';
import { getState, setState, subscribe, unsubscribe } from '/_102029_/l2/collabState.js';
import { runBlockingUiAction } from '/_102029_/l2/interactionRuntime.js';
import type { ConsultasContracts, AgendaCabecalho, ConsultaAgenda, ConsultaDetalhe, PacienteResumo, ProfissionalResumo } from '/_102047_/l2/agendaClinica/web/contracts/consultas.defs.js';
export type { ConsultasContracts, AgendaCabecalho, ConsultaAgenda, ConsultaDetalhe, PacienteResumo, ProfissionalResumo } from '/_102047_/l2/agendaClinica/web/contracts/consultas.defs.js';
export type ErrorState = { code: string; message: string; details?: unknown } | null;
export type AgendarConsultaDraft = { pacienteId: string | null; profissionalId: string | null; scheduledAt: string | null };
type Input<R extends keyof ConsultasContracts> = ConsultasContracts[R]['input'];
type Output<R extends keyof ConsultasContracts> = ConsultasContracts[R]['output'];
type AgendaPage = Output<'agendaClinica.consultas.carregarAgenda'>['agenda'];
type PatientPage = Output<'agendaClinica.consultas.localizarPacientesParaAgendamento'>['pacientes'];
type ProfessionalPage = Output<'agendaClinica.consultas.localizarProfissionaisParaAgendamento'>['profissionais'];
type StatusValue = Input<'agendaClinica.consultas.carregarAgenda'>['status'];
type StateMember = 'cabecalho' | 'quantidadePendentes' | 'agenda' | 'consulta' | 'pacientes' | 'profissionais' | 'selectedConsulta' | 'dataAgenda' | 'status' | 'page' | 'id' | 'termo' | 'pacienteId' | 'consultaId' | 'profissionalId' | 'agendarConsultaDraft' | 'pageStatus' | 'carregarAgendaStatus' | 'carregarAgendaError' | 'filtrarAgendaStatus' | 'filtrarAgendaError' | 'carregarMaisAgendaStatus' | 'carregarMaisAgendaError' | 'consultarConsultaSelecionadaStatus' | 'consultarConsultaSelecionadaError' | 'localizarPacientesParaAgendamentoStatus' | 'localizarPacientesParaAgendamentoError' | 'carregarMaisPacientesParaAgendamentoStatus' | 'carregarMaisPacientesParaAgendamentoError' | 'localizarProfissionaisParaAgendamentoStatus' | 'localizarProfissionaisParaAgendamentoError' | 'carregarMaisProfissionaisParaAgendamentoStatus' | 'carregarMaisProfissionaisParaAgendamentoError' | 'agendarConsultaStatus' | 'agendarConsultaError' | 'confirmarConsultaStatus' | 'confirmarConsultaError' | 'registrarFaltaStatus' | 'registrarFaltaError' | 'scenary';
const STATE_MEMBER_BY_KEY: Record<string, StateMember> = {
'ui.agendaClinica.consultas.cabecalho':'cabecalho','ui.agendaClinica.consultas.quantidadePendentes':'quantidadePendentes','ui.agendaClinica.consultas.agenda':'agenda','ui.agendaClinica.consultas.consulta':'consulta','ui.agendaClinica.consultas.pacientes':'pacientes','ui.agendaClinica.consultas.profissionais':'profissionais','ui.agendaClinica.consultas.selectedConsulta':'selectedConsulta','ui.agendaClinica.consultas.dataAgenda':'dataAgenda','ui.agendaClinica.consultas.status':'status','ui.agendaClinica.consultas.page':'page','ui.agendaClinica.consultas.id':'id','ui.agendaClinica.consultas.termo':'termo','ui.agendaClinica.consultas.pacienteId':'pacienteId','ui.agendaClinica.consultas.consultaId':'consultaId','ui.agendaClinica.consultas.profissionalId':'profissionalId','ui.agendaClinica.consultas.agendarConsultaDraft':'agendarConsultaDraft','ui.agendaClinica.consultas.pageStatus':'pageStatus','ui.agendaClinica.consultas.scenary':'scenary',
'ui.agendaClinica.consultas.carregarAgendaStatus':'carregarAgendaStatus','ui.agendaClinica.consultas.carregarAgendaError':'carregarAgendaError','ui.agendaClinica.consultas.filtrarAgendaStatus':'filtrarAgendaStatus','ui.agendaClinica.consultas.filtrarAgendaError':'filtrarAgendaError','ui.agendaClinica.consultas.carregarMaisAgendaStatus':'carregarMaisAgendaStatus','ui.agendaClinica.consultas.carregarMaisAgendaError':'carregarMaisAgendaError','ui.agendaClinica.consultas.consultarConsultaSelecionadaStatus':'consultarConsultaSelecionadaStatus','ui.agendaClinica.consultas.consultarConsultaSelecionadaError':'consultarConsultaSelecionadaError','ui.agendaClinica.consultas.localizarPacientesParaAgendamentoStatus':'localizarPacientesParaAgendamentoStatus','ui.agendaClinica.consultas.localizarPacientesParaAgendamentoError':'localizarPacientesParaAgendamentoError','ui.agendaClinica.consultas.carregarMaisPacientesParaAgendamentoStatus':'carregarMaisPacientesParaAgendamentoStatus','ui.agendaClinica.consultas.carregarMaisPacientesParaAgendamentoError':'carregarMaisPacientesParaAgendamentoError','ui.agendaClinica.consultas.localizarProfissionaisParaAgendamentoStatus':'localizarProfissionaisParaAgendamentoStatus','ui.agendaClinica.consultas.localizarProfissionaisParaAgendamentoError':'localizarProfissionaisParaAgendamentoError','ui.agendaClinica.consultas.carregarMaisProfissionaisParaAgendamentoStatus':'carregarMaisProfissionaisParaAgendamentoStatus','ui.agendaClinica.consultas.carregarMaisProfissionaisParaAgendamentoError':'carregarMaisProfissionaisParaAgendamentoError','ui.agendaClinica.consultas.agendarConsultaStatus':'agendarConsultaStatus','ui.agendaClinica.consultas.agendarConsultaError':'agendarConsultaError','ui.agendaClinica.consultas.confirmarConsultaStatus':'confirmarConsultaStatus','ui.agendaClinica.consultas.confirmarConsultaError':'confirmarConsultaError','ui.agendaClinica.consultas.registrarFaltaStatus':'registrarFaltaStatus','ui.agendaClinica.consultas.registrarFaltaError':'registrarFaltaError'};
const STATE_KEYS = Object.keys(STATE_MEMBER_BY_KEY);
const EMPTY_DRAFT = (): AgendarConsultaDraft => ({ pacienteId:null, profissionalId:null, scheduledAt:null });
export class AgendaClinicaConsultasShared extends StateLitElement {
/** state cabecalho — Cabeçalho da agenda no dia consultado.; source carregarAgenda.cabecalho; organisms listaAgenda */
@property({attribute:false}) cabecalho: AgendaCabecalho|null=null;
/** state quantidadePendentes — Devolve o cabeçalho da data, o indicador já calculado e uma página de linhas de agenda prontas para exibição.; source carregarAgenda.quantidadePendentes; organisms listaAgenda */
@property({attribute:false}) quantidadePendentes: number|null=null;
/** state agenda — Linha pronta para a agenda, com os nomes resolvidos do paciente e do profissional.; source carregarAgenda.agenda; organisms listaAgenda */
@property({attribute:false}) agenda: AgendaPage|null=null;
/** state consulta — Consulta selecionada, composta com paciente e profissional, para conferência, ações e preenchimento do formulário.; source consultarConsultaSelecionada.consulta; organisms acoesConsulta, detalheConsulta, formularioConsulta */
@property({attribute:false}) consulta: ConsultaDetalhe|null=null;
/** state pacientes — Paciente identificado em uma linha de agenda ou opção de agendamento.; source localizarPacientesParaAgendamento.pacientes; organisms formularioConsulta */
@property({attribute:false}) pacientes: PatientPage|null=null;
/** state profissionais — Profissional identificado em uma linha de agenda ou opção de agendamento.; source localizarProfissionaisParaAgendamento.profissionais; organisms formularioConsulta */
@property({attribute:false}) profissionais: ProfessionalPage|null=null;
/** state selectedConsulta — Consulta selecionada, composta com paciente e profissional, para conferência, ações e preenchimento do formulário.; source entry.params.consultaId; organisms detalheConsulta, listaAgenda */
@property({attribute:false}) selectedConsulta: string|null=null;
@property({attribute:false}) dataAgenda: string|null=null;
@property({attribute:false}) status: string|null=null;
@property({attribute:false}) page: number|null=null;
@property({attribute:false}) id: string='';
@property({attribute:false}) termo: string|null=null;
@property({attribute:false}) pacienteId: string|null=null;
@property({attribute:false}) consultaId: string|null=null;
@property({attribute:false}) profissionalId: string|null=null;
@property({attribute:false}) agendarConsultaDraft: AgendarConsultaDraft=EMPTY_DRAFT();
@property({attribute:false}) pageStatus: 'idle'|'loading'|'empty'|'success'|'error'='idle';
@property({attribute:false}) scenary='';
@property({attribute:false}) carregarAgendaStatus: 'idle'|'loading'|'success'|'error'='idle';
@property({attribute:false}) carregarAgendaError: ErrorState=null;
@property({attribute:false}) filtrarAgendaStatus: 'idle'|'loading'|'success'|'error'='idle';
@property({attribute:false}) filtrarAgendaError: ErrorState=null;
@property({attribute:false}) carregarMaisAgendaStatus: 'idle'|'loading'|'success'|'error'='idle';
@property({attribute:false}) carregarMaisAgendaError: ErrorState=null;
@property({attribute:false}) consultarConsultaSelecionadaStatus: 'idle'|'loading'|'success'|'error'='idle';
@property({attribute:false}) consultarConsultaSelecionadaError: ErrorState=null;
@property({attribute:false}) localizarPacientesParaAgendamentoStatus: 'idle'|'loading'|'success'|'error'='idle';
@property({attribute:false}) localizarPacientesParaAgendamentoError: ErrorState=null;
@property({attribute:false}) carregarMaisPacientesParaAgendamentoStatus: 'idle'|'loading'|'success'|'error'='idle';
@property({attribute:false}) carregarMaisPacientesParaAgendamentoError: ErrorState=null;
@property({attribute:false}) localizarProfissionaisParaAgendamentoStatus: 'idle'|'loading'|'success'|'error'='idle';
@property({attribute:false}) localizarProfissionaisParaAgendamentoError: ErrorState=null;
@property({attribute:false}) carregarMaisProfissionaisParaAgendamentoStatus: 'idle'|'loading'|'success'|'error'='idle';
@property({attribute:false}) carregarMaisProfissionaisParaAgendamentoError: ErrorState=null;
@property({attribute:false}) agendarConsultaStatus: 'idle'|'loading'|'success'|'error'='idle';
@property({attribute:false}) agendarConsultaError: ErrorState=null;
@property({attribute:false}) confirmarConsultaStatus: 'idle'|'loading'|'success'|'error'='idle';
@property({attribute:false}) confirmarConsultaError: ErrorState=null;
@property({attribute:false}) registrarFaltaStatus: 'idle'|'loading'|'success'|'error'='idle';
@property({attribute:false}) registrarFaltaError: ErrorState=null;
private publish<M extends StateMember>(member:M,value:this[M]):void {(this as unknown as Record<string,unknown>)[member]=value;setState(`ui.agendaClinica.consultas.${member}`,value);}
private publishDynamic(member:StateMember,value:unknown):void {(this as unknown as Record<string,unknown>)[member]=value;setState(`ui.agendaClinica.consultas.${member}`,value);}
private assignState(key:string,value:unknown):void {const member=STATE_MEMBER_BY_KEY[key];if(member)(this as unknown as Record<string,unknown>)[member]=value;}
private error(name:string,_error:unknown):ErrorState{return {code:'client.unexpected',message:'',details:{name}};}
private async query<R extends keyof ConsultasContracts>(request:R,input:Input<R>,status:StateMember,errorState:StateMember):Promise<Output<R>|null>{if((this as unknown as Record<string,unknown>)[status]==='loading')return null;this.publishDynamic(status,'loading');this.publishDynamic(errorState,null);try{const response=await execBff<Output<R>>(request,input,{mode:'silent'});if(!response.ok||!response.data){this.publishDynamic(errorState,response.error);this.publishDynamic(status,'error');return null;}this.publishDynamic(status,'success');return response.data;}catch(caught){this.publishDynamic(errorState,this.error(request,caught));this.publishDynamic(status,'error');return null;}}
private currentStatus():StatusValue {const value=this.status;if(value==='scheduled'||value==='confirmed'||value==='noShow'||value==='attended')return value;return undefined;}
private agendaInput(page:number):Input<'agendaClinica.consultas.carregarAgenda'>|null{if(!this.dataAgenda)return null;const status=this.currentStatus();return {dataAgenda:this.dataAgenda,page,pageSize:20,...(status?{status}:{})};}
private async applyAgenda(output:{cabecalho:AgendaCabecalho;quantidadePendentes:number;agenda:AgendaPage}):Promise<void>{this.publish('cabecalho',output.cabecalho);this.publish('quantidadePendentes',output.quantidadePendentes);this.publish('agenda',output.agenda);}
public async carregarAgenda():Promise<void>{this.publish('pageStatus','loading');const input=this.agendaInput(this.page&&this.page>0?this.page:1);if(!input){this.publish('pageStatus','error');return;}const output=await this.query('agendaClinica.consultas.carregarAgenda',input,'carregarAgendaStatus','carregarAgendaError');if(!output){this.publish('pageStatus','error');return;}await this.applyAgenda(output);this.publish('pageStatus',output.agenda.items.length===0?'empty':'success');}
public async filtrarAgenda():Promise<void>{const input=this.agendaInput(1);if(!input)return;const output=await this.query('agendaClinica.consultas.filtrarAgenda',input,'filtrarAgendaStatus','filtrarAgendaError');if(output)await this.applyAgenda(output);}
public async carregarMaisAgenda():Promise<void>{if(!this.agenda||!this.agenda.hasMore)return;const input=this.agendaInput(this.agenda.page+1);if(!input)return;const output=await this.query('agendaClinica.consultas.carregarMaisAgenda',input,'carregarMaisAgendaStatus','carregarMaisAgendaError');if(!output)return;this.publish('agenda',{...output.agenda,items:[...this.agenda.items,...output.agenda.items]});}
public async consultarConsultaSelecionada():Promise<void>{const selected=this.selectedConsulta??this.consultaId??(this.id||null);if(!selected)return;const output=await this.query('agendaClinica.consultas.consultarConsultaSelecionada',{id:selected},'consultarConsultaSelecionadaStatus','consultarConsultaSelecionadaError');if(output)this.publish('consulta',output.consulta);}
public async localizarPacientesParaAgendamento():Promise<void>{const output=await this.query('agendaClinica.consultas.localizarPacientesParaAgendamento',{termo:this.termo??'',page:1,pageSize:20},'localizarPacientesParaAgendamentoStatus','localizarPacientesParaAgendamentoError');if(output)this.publish('pacientes',output.pacientes);}
public async carregarMaisPacientesParaAgendamento():Promise<void>{if(!this.pacientes||!this.pacientes.hasMore)return;const output=await this.query('agendaClinica.consultas.carregarMaisPacientesParaAgendamento',{termo:this.termo??'',page:this.pacientes.page+1,pageSize:20},'carregarMaisPacientesParaAgendamentoStatus','carregarMaisPacientesParaAgendamentoError');if(!output||!this.pacientes)return;this.publish('pacientes',{...output.pacientes,items:[...this.pacientes.items,...output.pacientes.items]});}
public async localizarProfissionaisParaAgendamento():Promise<void>{const output=await this.query('agendaClinica.consultas.localizarProfissionaisParaAgendamento',{termo:this.termo??'',page:1,pageSize:20},'localizarProfissionaisParaAgendamentoStatus','localizarProfissionaisParaAgendamentoError');if(output)this.publish('profissionais',output.profissionais);}
public async carregarMaisProfissionaisParaAgendamento():Promise<void>{if(!this.profissionais||!this.profissionais.hasMore)return;const output=await this.query('agendaClinica.consultas.carregarMaisProfissionaisParaAgendamento',{termo:this.termo??'',page:this.profissionais.page+1,pageSize:20},'carregarMaisProfissionaisParaAgendamentoStatus','carregarMaisProfissionaisParaAgendamentoError');if(!output||!this.profissionais)return;this.publish('profissionais',{...output.profissionais,items:[...this.profissionais.items,...output.profissionais.items]});}
public setAgendarConsultaDraft(value:AgendarConsultaDraft):void{this.publish('agendarConsultaDraft',value);}
public async selectConsulta(value:string|null):Promise<void>{this.publish('consultaId',value);this.publish('selectedConsulta',value);if(value)await this.consultarConsultaSelecionada();}
private async command<R extends keyof ConsultasContracts>(request:R,input:Input<R>,status:StateMember,errorState:StateMember):Promise<Output<R>|null>{this.publishDynamic(status,'loading');this.publishDynamic(errorState,null);const result=await runBlockingUiAction(signal=>execBff<Output<R>>(request,input,{mode:'blocking',signal}));if(!result){this.publishDynamic(errorState,{code:'client.unexpected',message:'',details:{name:'aborted'}});this.publishDynamic(status,'error');return null;}if(!result.ok||!result.data){this.publishDynamic(errorState,result.error);this.publishDynamic(status,'error');return null;}this.publishDynamic(status,'success');return result.data;}
private commandAgenda():{dataAgenda:string;statusAgenda?:StatusValue;page:number;pageSize:number}|null{if(!this.dataAgenda)return null;const status=this.currentStatus();return {dataAgenda:this.dataAgenda,page:this.agenda?.page??1,pageSize:20,...(status?{statusAgenda:status}:{})};}
public async agendarConsulta():Promise<void>{const draft=this.agendarConsultaDraft;const context=this.commandAgenda();const pacienteId=draft.pacienteId;const profissionalId=draft.profissionalId;const scheduledAt=draft.scheduledAt;const missing:string[]=[];if(!pacienteId)missing.push('agendarConsultaDraft.pacienteId');if(!profissionalId)missing.push('agendarConsultaDraft.profissionalId');if(!scheduledAt)missing.push('agendarConsultaDraft.scheduledAt');if(!context)missing.push('dataAgenda');if(missing.length>0||!pacienteId||!profissionalId||!scheduledAt||!context){this.publish('agendarConsultaError',{code:'client.requiredMissing',message:'',details:{stateKeys:missing}});this.publish('agendarConsultaStatus','error');return;}const output=await this.command('agendaClinica.consultas.agendarConsulta',{pacienteId,profissionalId,scheduledAt,...context},'agendarConsultaStatus','agendarConsultaError');if(!output)return;this.publish('consulta',output.consulta);await this.applyAgenda(output);this.publish('agendarConsultaDraft',EMPTY_DRAFT());}
public async confirmarConsulta():Promise<void>{const context=this.commandAgenda();if(!this.consulta||!context)return;const output=await this.command('agendaClinica.consultas.confirmarConsulta',{id:this.consulta.id,version:this.consulta.version,...context},'confirmarConsultaStatus','confirmarConsultaError');if(output){this.publish('consulta',output.consulta);await this.applyAgenda(output);}}
public async registrarFalta():Promise<void>{const context=this.commandAgenda();if(!this.consulta||!context)return;const output=await this.command('agendaClinica.consultas.registrarFalta',{id:this.consulta.id,version:this.consulta.version,...context},'registrarFaltaStatus','registrarFaltaError');if(output){this.publish('consulta',output.consulta);await this.applyAgenda(output);}}
public setScenario(value:string):void{this.publish('scenary',value);}
public connectedCallback():void{super.connectedCallback();this.resetVisit();for(const key of STATE_KEYS){const member=STATE_MEMBER_BY_KEY[key];if(!['pageStatus','scenary','agendarConsultaDraft'].includes(member)&&!member.endsWith('Status')&&!member.endsWith('Error')){const value=getState(key);if(value!==undefined)this.assignState(key,value);}}subscribe(STATE_KEYS,this);this.applyEntryParams();void this.carregarAgenda();}
public disconnectedCallback():void{unsubscribe(STATE_KEYS,this);super.disconnectedCallback();}
private resetVisit():void{this.publish('pageStatus','idle');this.publish('scenary','');this.publish('agendarConsultaDraft',EMPTY_DRAFT());this.publish('filtrarAgendaStatus','idle');this.publish('filtrarAgendaError',null);this.publish('carregarMaisAgendaStatus','idle');this.publish('carregarMaisAgendaError',null);this.publish('consultarConsultaSelecionadaStatus','idle');this.publish('consultarConsultaSelecionadaError',null);this.publish('localizarPacientesParaAgendamentoStatus','idle');this.publish('localizarPacientesParaAgendamentoError',null);this.publish('carregarMaisPacientesParaAgendamentoStatus','idle');this.publish('carregarMaisPacientesParaAgendamentoError',null);this.publish('localizarProfissionaisParaAgendamentoStatus','idle');this.publish('localizarProfissionaisParaAgendamentoError',null);this.publish('carregarMaisProfissionaisParaAgendamentoStatus','idle');this.publish('carregarMaisProfissionaisParaAgendamentoError',null);this.publish('agendarConsultaStatus','idle');this.publish('agendarConsultaError',null);this.publish('confirmarConsultaStatus','idle');this.publish('confirmarConsultaError',null);this.publish('registrarFaltaStatus','idle');this.publish('registrarFaltaError',null);}
private applyEntryParams():void{const params=new URLSearchParams(window.location.search);const names=['dataAgenda','status','page','id','termo','pacienteId','consultaId','profissionalId'];for(const name of names){let raw=params.get(name);if(raw===null){try{raw=localStorage.getItem(`agendaClinica.consultas.${name}`);}catch{raw=null;}}if(name==='page'){const numberValue=raw===null?null:Number(raw);if(numberValue!==null&&Number.isFinite(numberValue))this.publish('page',numberValue);}else if(name==='consultaId'){this.publish('consultaId',raw);this.publish('selectedConsulta',raw);}else if(name==='dataAgenda')this.publish('dataAgenda',raw);else if(name==='status')this.publish('status',raw);else if(name==='id'){if(raw!==null)this.publish('id',raw);}else if(name==='termo')this.publish('termo',raw);else if(name==='pacienteId')this.publish('pacienteId',raw);else if(name==='profissionalId'){this.publish('profissionalId',raw);const draft=this.agendarConsultaDraft;this.publish('agendarConsultaDraft',{...draft,profissionalId:raw});}}}
public handleIcaStateChange(key:string,value:any):void{if(!STATE_MEMBER_BY_KEY[key]){super.handleIcaStateChange(key,value);return;}if(value===undefined)return;this.assignState(key,value);this.requestUpdate();}
}
