/// <mls fileReference="_102047_/l2/agendaClinica/web/shared/consultas.ts" enhancement="_102020_/l2/enhancementAura"/>

import { StateLitElement } from '/_102029_/l2/stateLitElement.js';
import { execBff, type BffClientOptions } from '/_102029_/l2/bffClient.js';
import { getState, setState, subscribe, unsubscribe } from '/_102029_/l2/collabState.js';
import { runBlockingUiAction } from '/_102029_/l2/interactionRuntime.js';
import {
 createConsultaRoute, registrarFaltaRoute, updateConsultaRoute, listConsultaRoute, listPacienteRoute, listProfissionalRoute,
 type CreateConsultaInput, type CreateConsultaOutput, type RegistrarFaltaInput, type RegistrarFaltaOutput,
 type UpdateConsultaInput, type UpdateConsultaOutput, type ListConsultaInput, type ListConsultaOutput,
 type ListPacienteInput, type ListPacienteOutput, type ListProfissionalInput, type ListProfissionalOutput,
} from '../contracts/consultas.defs.js';
type ErrorState = { code: string; message: string; details?: unknown };
type PageStatus = 'idle' | 'loading' | 'empty' | 'success' | 'error';
type ActionStatus = 'idle' | 'loading' | 'success' | 'error';
type Scenary = 'base' | 'detailConsulta' | 'createConsulta' | 'updateConsulta';
type ConsultaStatus = 'scheduled' | 'noShow' | 'attended';
type PacienteDocType = 'CPF' | 'NationalId' | 'Passport' | 'Other';
type ProfissionalStatus = 'Active' | 'Inactive' | 'Merged' | 'Blocked';
type ErrorEnvelope = { code?: unknown; message: string; details?: unknown };
const K = {
 pageStatus:'ui.consultas.pageStatus', scenary:'ui.consultas.scenary',
 createPaciente:'ui.consultas.createConsulta.input.pacienteId', createProfissional:'ui.consultas.createConsulta.input.profissionalId', createScheduled:'ui.consultas.createConsulta.input.scheduledAt', createConfirmed:'ui.consultas.createConsulta.input.details.telephoneConfirmation.confirmedAt', createStatus:'ui.consultas.createConsulta.status', createError:'ui.consultas.createConsulta.error', createResult:'ui.consultas.createConsulta.result',
 faltaId:'ui.consultas.registrarFalta.input.id', faltaStatus:'ui.consultas.registrarFalta.status', faltaError:'ui.consultas.registrarFalta.error', faltaResult:'ui.consultas.registrarFalta.result',
 updateId:'ui.consultas.updateConsulta.input.id', updatePaciente:'ui.consultas.updateConsulta.input.pacienteId', updateProfissional:'ui.consultas.updateConsulta.input.profissionalId', updateScheduled:'ui.consultas.updateConsulta.input.scheduledAt', updateConfirmed:'ui.consultas.updateConsulta.input.details.telephoneConfirmation.confirmedAt', updateStatus:'ui.consultas.updateConsulta.status', updateError:'ui.consultas.updateConsulta.error', updateResult:'ui.consultas.updateConsulta.result',
 listId:'ui.consultas.listConsulta.input.id', listPaciente:'ui.consultas.listConsulta.input.pacienteId', listProfissional:'ui.consultas.listConsulta.input.profissionalId', listScheduled:'ui.consultas.listConsulta.input.scheduledAt', listInputStatus:'ui.consultas.listConsulta.input.status', listPage:'ui.consultas.listConsulta.input.page', listStatus:'ui.consultas.listConsulta.status', listError:'ui.consultas.listConsulta.error', listResult:'ui.consultas.listConsulta.result',
 pacienteId:'ui.consultas.listPaciente.input.id', pacienteSubtype:'ui.consultas.listPaciente.input.details.identification.subtype', pacienteName:'ui.consultas.listPaciente.input.details.identification.name', pacienteDocType:'ui.consultas.listPaciente.input.details.identification.docType', pacienteDocId:'ui.consultas.listPaciente.input.details.identification.docId', pacienteCountry:'ui.consultas.listPaciente.input.details.identification.countryCode', pacientePage:'ui.consultas.listPaciente.input.page', pacienteStatus:'ui.consultas.listPaciente.status', pacienteError:'ui.consultas.listPaciente.error', pacienteResult:'ui.consultas.listPaciente.result',
 profissionalId:'ui.consultas.listProfissional.input.id', profissionalSubtype:'ui.consultas.listProfissional.input.details.identification.subtype', profissionalName:'ui.consultas.listProfissional.input.details.identification.name', profissionalStatusInput:'ui.consultas.listProfissional.input.details.identification.status', profissionalDocType:'ui.consultas.listProfissional.input.details.identification.docType', profissionalDocId:'ui.consultas.listProfissional.input.details.identification.docId', profissionalCountry:'ui.consultas.listProfissional.input.details.identification.countryCode', profissionalPage:'ui.consultas.listProfissional.input.page', profissionalStatus:'ui.consultas.listProfissional.status', profissionalError:'ui.consultas.listProfissional.error', profissionalResult:'ui.consultas.listProfissional.result',
} as const;
const listConsultaInputStatusMember = 'stateListConsultaStatusX00007300007400006100007400006500003a00007500006900002e00006300006f00006e00007300007500006c00007400006100007300002e00006c00006900007300007400004300006f00006e00007300007500006c00007400006100002e00006900006e00007000007500007400002e000073000074000061000074000075000073' as const;
const listConsultaStatusMember = 'stateListConsultaStatusX00007300007400006100007400006500003a00007500006900002e00006300006f00006e00007300007500006c00007400006100007300002e00006c00006900007300007400004300006f00006e00007300007500006c00007400006100002e000073000074000061000074000075000073' as const;
export class ConsultasShared extends StateLitElement {
 public pageStatus: PageStatus='idle'; public scenary: Scenary='base';
 public stateCreateConsultaPacienteId:string|null=null; public stateCreateConsultaProfissionalId:string|null=null; public stateCreateConsultaScheduledAt:string|null=null; public stateCreateConsultaDetailsTelephoneConfirmationConfirmedAt:string|null=null; public stateCreateConsultaStatus:ActionStatus='idle'; public stateCreateConsultaError:ErrorState|null=null; public stateCreateConsultaResult:CreateConsultaOutput|null=null;
 public stateRegistrarFaltaId:string|null=null; public stateRegistrarFaltaStatus:ActionStatus='idle'; public stateRegistrarFaltaError:ErrorState|null=null; public stateRegistrarFaltaResult:RegistrarFaltaOutput|null=null;
 public stateUpdateConsultaId:string|null=null; public stateUpdateConsultaPacienteId:string|null=null; public stateUpdateConsultaProfissionalId:string|null=null; public stateUpdateConsultaScheduledAt:string|null=null; public stateUpdateConsultaDetailsTelephoneConfirmationConfirmedAt:string|null=null; public stateUpdateConsultaStatus:ActionStatus='idle'; public stateUpdateConsultaError:ErrorState|null=null; public stateUpdateConsultaResult:UpdateConsultaOutput|null=null;
 public stateListConsultaId:string|null=null; public stateListConsultaPacienteId:string|null=null; public stateListConsultaProfissionalId:string|null=null; public stateListConsultaScheduledAt:string|null=null;
 public stateListConsultaStatusX00007300007400006100007400006500003a00007500006900002e00006300006f00006e00007300007500006c00007400006100007300002e00006c00006900007300007400004300006f00006e00007300007500006c00007400006100002e00006900006e00007000007500007400002e000073000074000061000074000075000073: ConsultaStatus|null=null;
 public stateListConsultaPage:number|null=null;
 public stateListConsultaStatusX00007300007400006100007400006500003a00007500006900002e00006300006f00006e00007300007500006c00007400006100007300002e00006c00006900007300007400004300006f00006e00007300007500006c00007400006100002e000073000074000061000074000075000073:ActionStatus='idle'; public stateListConsultaError:ErrorState|null=null; public stateListConsultaResult:ListConsultaOutput=[];
 public stateListPacienteId:string|null=null; public stateListPacienteDetailsIdentificationSubtype:'Person'|null=null; public stateListPacienteDetailsIdentificationName:string|null=null; public stateListPacienteDetailsIdentificationDocType:PacienteDocType|null=null; public stateListPacienteDetailsIdentificationDocId:string|null=null; public stateListPacienteDetailsIdentificationCountryCode:string|null=null; public stateListPacientePage:number|null=null; public stateListPacienteStatus:ActionStatus='idle'; public stateListPacienteError:ErrorState|null=null; public stateListPacienteResult:ListPacienteOutput=[];
 public stateListProfissionalId:string|null=null; public stateListProfissionalDetailsIdentificationSubtype:'Person'|null=null; public stateListProfissionalDetailsIdentificationName:string|null=null; public stateListProfissionalDetailsIdentificationStatus:ProfissionalStatus|null=null; public stateListProfissionalDetailsIdentificationDocType:PacienteDocType|null=null; public stateListProfissionalDetailsIdentificationDocId:string|null=null; public stateListProfissionalDetailsIdentificationCountryCode:string|null=null; public stateListProfissionalPage:number|null=null; public stateListProfissionalStatus:ActionStatus='idle'; public stateListProfissionalError:ErrorState|null=null; public stateListProfissionalResult:ListProfissionalOutput=[];
 private readonly subscribedKeys=Object.values(K); private readonly loading=new Set<string>();
 public connectedCallback():void { super.connectedCallback(); this.hydrate(); this.subscribedKeys.forEach((key:string)=>subscribe([key],this)); void this.runListConsulta(); void this.runListPaciente(); void this.runListProfissional(); }
 public disconnectedCallback():void { this.subscribedKeys.forEach((key:string)=>unsubscribe([key],this)); super.disconnectedCallback(); }
 public handleIcaStateChange(key:string,value:unknown):void { if (value === undefined) return; const map:Record<string,string>={ [K.pageStatus]:'pageStatus',[K.scenary]:'scenary',[K.createPaciente]:'stateCreateConsultaPacienteId',[K.createProfissional]:'stateCreateConsultaProfissionalId',[K.createScheduled]:'stateCreateConsultaScheduledAt',[K.createConfirmed]:'stateCreateConsultaDetailsTelephoneConfirmationConfirmedAt',[K.createStatus]:'stateCreateConsultaStatus',[K.createError]:'stateCreateConsultaError',[K.createResult]:'stateCreateConsultaResult',[K.faltaId]:'stateRegistrarFaltaId',[K.faltaStatus]:'stateRegistrarFaltaStatus',[K.faltaError]:'stateRegistrarFaltaError',[K.faltaResult]:'stateRegistrarFaltaResult',[K.updateId]:'stateUpdateConsultaId',[K.updatePaciente]:'stateUpdateConsultaPacienteId',[K.updateProfissional]:'stateUpdateConsultaProfissionalId',[K.updateScheduled]:'stateUpdateConsultaScheduledAt',[K.updateConfirmed]:'stateUpdateConsultaDetailsTelephoneConfirmationConfirmedAt',[K.updateStatus]:'stateUpdateConsultaStatus',[K.updateError]:'stateUpdateConsultaError',[K.updateResult]:'stateUpdateConsultaResult',[K.listId]:'stateListConsultaId',[K.listPaciente]:'stateListConsultaPacienteId',[K.listProfissional]:'stateListConsultaProfissionalId',[K.listScheduled]:'stateListConsultaScheduledAt',[K.listInputStatus]:listConsultaInputStatusMember,[K.listPage]:'stateListConsultaPage',[K.listStatus]:listConsultaStatusMember,[K.listError]:'stateListConsultaError',[K.listResult]:'stateListConsultaResult',[K.pacienteId]:'stateListPacienteId',[K.pacienteSubtype]:'stateListPacienteDetailsIdentificationSubtype',[K.pacienteName]:'stateListPacienteDetailsIdentificationName',[K.pacienteDocType]:'stateListPacienteDetailsIdentificationDocType',[K.pacienteDocId]:'stateListPacienteDetailsIdentificationDocId',[K.pacienteCountry]:'stateListPacienteDetailsIdentificationCountryCode',[K.pacientePage]:'stateListPacientePage',[K.pacienteStatus]:'stateListPacienteStatus',[K.pacienteError]:'stateListPacienteError',[K.pacienteResult]:'stateListPacienteResult',[K.profissionalId]:'stateListProfissionalId',[K.profissionalSubtype]:'stateListProfissionalDetailsIdentificationSubtype',[K.profissionalName]:'stateListProfissionalDetailsIdentificationName',[K.profissionalStatusInput]:'stateListProfissionalDetailsIdentificationStatus',[K.profissionalDocType]:'stateListProfissionalDetailsIdentificationDocType',[K.profissionalDocId]:'stateListProfissionalDetailsIdentificationDocId',[K.profissionalCountry]:'stateListProfissionalDetailsIdentificationCountryCode',[K.profissionalPage]:'stateListProfissionalPage',[K.profissionalStatus]:'stateListProfissionalStatus',[K.profissionalError]:'stateListProfissionalError',[K.profissionalResult]:'stateListProfissionalResult' }; const member=map[key]; if(member){(this as unknown as Record<string,unknown>)[member]=value;this.requestUpdate();} }
 private hydrate():void { this.subscribedKeys.forEach((key:string)=>{const value=getState(key);if(value!==undefined)this.handleIcaStateChange(key,value);}); }
 private publish<T>(key:string,member:string,value:T):void { setState(key,value); (this as unknown as Record<string,unknown>)[member]=value; this.requestUpdate(); }
 private has(value:unknown):boolean{return value!==null&&value!==undefined&&!(typeof value==='string'&&value.length===0);}
 private feedback(error:unknown,fallback:string):ErrorState { if(error&&typeof error==='object'&&'message' in error&&typeof error.message==='string'){const e=error as ErrorEnvelope;return {code:typeof e.code==='string'?e.code:'UNEXPECTED_ERROR',message:e.message,details:e.details};} return {code:'UNEXPECTED_ERROR',message:fallback}; }
 private required(values:Array<[string,unknown]>):ErrorState|null { const missing=values.find((entry:[string,unknown])=>!this.has(entry[1])); return missing?{code:'MISSING_REQUIRED_INPUT',message:`Informe ${missing[0]}.`}:null; }
 private async call<T>(route:string,params:unknown,options?:BffClientOptions):Promise<{ok:boolean;data:T|null;error:ErrorState|null}>{return execBff<T>(route,params,options);}
 private confirm(title:string,description:string):boolean{return typeof window==='undefined'||window.confirm(`${title}\n\n${description}`);}
 public setScenario(value:Scenary):void{this.publish(K.scenary,'scenary',value);}
 public selectCreateConsultaPacienteId(id:string|null):void{this.select(K.createPaciente,'stateCreateConsultaPacienteId',id,K.pacienteResult);}
 public selectCreateConsultaProfissionalId(id:string|null):void{this.select(K.createProfissional,'stateCreateConsultaProfissionalId',id,K.profissionalResult);}
 public setCreateConsultaScheduledAt(value:string|null):void{this.publish(K.createScheduled,'stateCreateConsultaScheduledAt',value);}
 public setCreateConsultaDetailsTelephoneConfirmationConfirmedAt(value:string|null):void{this.publish(K.createConfirmed,'stateCreateConsultaDetailsTelephoneConfirmationConfirmedAt',value);}
 public selectRegistrarFaltaId(id:string|null):void{this.select(K.faltaId,'stateRegistrarFaltaId',id,K.listResult);}
 public selectUpdateConsultaId(id:string|null):void{this.select(K.updateId,'stateUpdateConsultaId',id,K.listResult);}
 public selectUpdateConsultaPacienteId(id:string|null):void{this.select(K.updatePaciente,'stateUpdateConsultaPacienteId',id,K.pacienteResult);}
 public selectUpdateConsultaProfissionalId(id:string|null):void{this.select(K.updateProfissional,'stateUpdateConsultaProfissionalId',id,K.profissionalResult);}
 public setUpdateConsultaScheduledAt(value:string|null):void{this.publish(K.updateScheduled,'stateUpdateConsultaScheduledAt',value);}
 public setUpdateConsultaDetailsTelephoneConfirmationConfirmedAt(value:string|null):void{this.publish(K.updateConfirmed,'stateUpdateConsultaDetailsTelephoneConfirmationConfirmedAt',value);}
 private select(key:string,member:string,id:string|null,resultKey:string):void{if(id===null){this.publish(key,member,null);return;}const rows=getState(resultKey) as Array<{id?:string}>|undefined;if(rows?.some((row:{id?:string})=>row.id===id))this.publish(key,member,id);}
 public setListConsultaId(value:string|null):void{this.publish(K.listId,'stateListConsultaId',value);}
 public selectListConsultaPacienteId(id:string|null):void{this.select(K.listPaciente,'stateListConsultaPacienteId',id,K.pacienteResult);}
 public selectListConsultaProfissionalId(id:string|null):void{this.select(K.listProfissional,'stateListConsultaProfissionalId',id,K.profissionalResult);}
 public setListConsultaScheduledAt(value:string|null):void{this.publish(K.listScheduled,'stateListConsultaScheduledAt',value);}
 public setListConsultaStatus(value:ConsultaStatus|null):void{this.publish(K.listInputStatus,listConsultaInputStatusMember,value);}
 public setListPacienteId(value:string|null):void{this.publish(K.pacienteId,'stateListPacienteId',value);}
 public setListPacienteDetailsIdentificationSubtype(value:'Person'|null):void{this.publish(K.pacienteSubtype,'stateListPacienteDetailsIdentificationSubtype',value);}
 public setListPacienteDetailsIdentificationName(value:string|null):void{this.publish(K.pacienteName,'stateListPacienteDetailsIdentificationName',value);}
 public setListPacienteDetailsIdentificationDocType(value:PacienteDocType|null):void{this.publish(K.pacienteDocType,'stateListPacienteDetailsIdentificationDocType',value);}
 public setListPacienteDetailsIdentificationDocId(value:string|null):void{this.publish(K.pacienteDocId,'stateListPacienteDetailsIdentificationDocId',value);}
 public setListPacienteDetailsIdentificationCountryCode(value:string|null):void{this.publish(K.pacienteCountry,'stateListPacienteDetailsIdentificationCountryCode',value);}
 public setListProfissionalId(value:string|null):void{this.publish(K.profissionalId,'stateListProfissionalId',value);}
 public setListProfissionalDetailsIdentificationSubtype(value:'Person'|null):void{this.publish(K.profissionalSubtype,'stateListProfissionalDetailsIdentificationSubtype',value);}
 public setListProfissionalDetailsIdentificationName(value:string|null):void{this.publish(K.profissionalName,'stateListProfissionalDetailsIdentificationName',value);}
 public setListProfissionalDetailsIdentificationStatus(value:ProfissionalStatus|null):void{this.publish(K.profissionalStatusInput,'stateListProfissionalDetailsIdentificationStatus',value);}
 public setListProfissionalDetailsIdentificationDocType(value:PacienteDocType|null):void{this.publish(K.profissionalDocType,'stateListProfissionalDetailsIdentificationDocType',value);}
 public setListProfissionalDetailsIdentificationDocId(value:string|null):void{this.publish(K.profissionalDocId,'stateListProfissionalDetailsIdentificationDocId',value);}
 public setListProfissionalDetailsIdentificationCountryCode(value:string|null):void{this.publish(K.profissionalCountry,'stateListProfissionalDetailsIdentificationCountryCode',value);}
 public async runCreateConsulta():Promise<void>{if(this.loading.has('createConsulta'))return;const missing=this.required([['Paciente',this.stateCreateConsultaPacienteId],['Profissional',this.stateCreateConsultaProfissionalId],['Data e horário',this.stateCreateConsultaScheduledAt],['Confirmação telefônica',this.stateCreateConsultaDetailsTelephoneConfirmationConfirmedAt]]);if(missing){this.publish(K.createError,'stateCreateConsultaError',missing);this.publish(K.createStatus,'stateCreateConsultaStatus','error');return;}const params:CreateConsultaInput={pacienteId:this.stateCreateConsultaPacienteId as string,profissionalId:this.stateCreateConsultaProfissionalId as string,scheduledAt:this.stateCreateConsultaScheduledAt as string,details:{telephoneConfirmation:{confirmedAt:this.stateCreateConsultaDetailsTelephoneConfirmationConfirmedAt as string}}};await this.command('createConsulta',K.createStatus,'stateCreateConsultaStatus',K.createError,'stateCreateConsultaError',K.createResult,'stateCreateConsultaResult',createConsultaRoute,params,['runListConsulta']);}
 public async runRegistrarFalta():Promise<void>{if(!this.confirm('Registrar falta do paciente','Confirme que o paciente não compareceu à consulta agendada. A consulta será marcada como falta.'))return;const missing=this.required([['Id',this.stateRegistrarFaltaId]]);if(missing){this.publish(K.faltaError,'stateRegistrarFaltaError',missing);this.publish(K.faltaStatus,'stateRegistrarFaltaStatus','error');return;}await this.command('registrarFalta',K.faltaStatus,'stateRegistrarFaltaStatus',K.faltaError,'stateRegistrarFaltaError',K.faltaResult,'stateRegistrarFaltaResult',registrarFaltaRoute,{id:this.stateRegistrarFaltaId as string},['runListConsulta']);}
 public async runUpdateConsulta():Promise<void>{const missing=this.required([['Id',this.stateUpdateConsultaId],['Paciente',this.stateUpdateConsultaPacienteId],['Profissional',this.stateUpdateConsultaProfissionalId],['Data e horário',this.stateUpdateConsultaScheduledAt],['Confirmação telefônica',this.stateUpdateConsultaDetailsTelephoneConfirmationConfirmedAt]]);if(missing){this.publish(K.updateError,'stateUpdateConsultaError',missing);this.publish(K.updateStatus,'stateUpdateConsultaStatus','error');return;}const params:UpdateConsultaInput={id:this.stateUpdateConsultaId as string,pacienteId:this.stateUpdateConsultaPacienteId as string,profissionalId:this.stateUpdateConsultaProfissionalId as string,scheduledAt:this.stateUpdateConsultaScheduledAt as string,details:{telephoneConfirmation:{confirmedAt:this.stateUpdateConsultaDetailsTelephoneConfirmationConfirmedAt as string}}};await this.command('updateConsulta',K.updateStatus,'stateUpdateConsultaStatus',K.updateError,'stateUpdateConsultaError',K.updateResult,'stateUpdateConsultaResult',updateConsultaRoute,params,['runListConsulta']);}
 private async command<T>(name:string,statusKey:string,statusMember:string,errorKey:string,errorMember:string,resultKey:string,resultMember:string,route:string,params:unknown,refresh:string[]):Promise<void>{if(this.loading.has(name))return;this.loading.add(name);this.publish(errorKey,errorMember,null);this.publish(statusKey,statusMember,'loading');try{const response=await runBlockingUiAction((signal:AbortSignal)=>this.call<T>(route,params,{mode:'blocking',signal}),{mode:'blocking'});if(!response)throw new Error('Ação interrompida.');if(response.ok&&response.data!==null){this.publish(resultKey,resultMember,response.data);this.publish(statusKey,statusMember,'success');for(const action of refresh)if(action==='runListConsulta')await this.runListConsulta();}else{const envelope=response.error;const feedback=this.feedback(envelope&&typeof envelope==='object'&&'message' in envelope&&typeof envelope.message==='string'?envelope:'Não foi possível concluir a ação.','Não foi possível concluir a ação.');this.publish(errorKey,errorMember,feedback);this.publish(statusKey,statusMember,'error');}}catch(error:unknown){const feedback=this.feedback(error,'Não foi possível concluir a ação.');this.publish(errorKey,errorMember,feedback);this.publish(statusKey,statusMember,'error');}finally{this.loading.delete(name);}}
 public async runListConsulta():Promise<void>{const params:ListConsultaInput={};if(this.has(this.stateListConsultaId))params.id=this.stateListConsultaId as string;if(this.has(this.stateListConsultaPacienteId))params.pacienteId=this.stateListConsultaPacienteId as string;if(this.has(this.stateListConsultaProfissionalId))params.profissionalId=this.stateListConsultaProfissionalId as string;if(this.has(this.stateListConsultaScheduledAt))params.scheduledAt=this.stateListConsultaScheduledAt as string;const status=this.stateListConsultaStatusX00007300007400006100007400006500003a00007500006900002e00006300006f00006e00007300007500006c00007400006100007300002e00006c00006900007300007400004300006f00006e00007300007500006c00007400006100002e00006900006e00007000007500007400002e000073000074000061000074000075000073;if(status!==null)params.status=status;if(this.stateListConsultaPage!==null)params.page=this.stateListConsultaPage;await this.query(K.listStatus,listConsultaStatusMember,K.listError,'stateListConsultaError',K.listResult,'stateListConsultaResult',listConsultaRoute,params);}
 public async runListPaciente():Promise<void>{const params:ListPacienteInput={};if(this.has(this.stateListPacienteId))params.id=this.stateListPacienteId as string;const identification:NonNullable<NonNullable<ListPacienteInput['details']>['identification']>={};if(this.stateListPacienteDetailsIdentificationSubtype!==null)identification.subtype=this.stateListPacienteDetailsIdentificationSubtype;if(this.has(this.stateListPacienteDetailsIdentificationName))identification.name=this.stateListPacienteDetailsIdentificationName as string;if(this.stateListPacienteDetailsIdentificationDocType!==null)identification.docType=this.stateListPacienteDetailsIdentificationDocType;if(this.has(this.stateListPacienteDetailsIdentificationDocId))identification.docId=this.stateListPacienteDetailsIdentificationDocId as string;if(this.has(this.stateListPacienteDetailsIdentificationCountryCode))identification.countryCode=this.stateListPacienteDetailsIdentificationCountryCode as string;if(Object.keys(identification).length)params.details={identification};if(this.stateListPacientePage!==null)params.page=this.stateListPacientePage;await this.query(K.pacienteStatus,'stateListPacienteStatus',K.pacienteError,'stateListPacienteError',K.pacienteResult,'stateListPacienteResult',listPacienteRoute,params);}
 public async runListProfissional():Promise<void>{const params:ListProfissionalInput={};if(this.has(this.stateListProfissionalId))params.id=this.stateListProfissionalId as string;const identification:NonNullable<NonNullable<ListProfissionalInput['details']>['identification']>={};if(this.stateListProfissionalDetailsIdentificationSubtype!==null)identification.subtype=this.stateListProfissionalDetailsIdentificationSubtype;if(this.has(this.stateListProfissionalDetailsIdentificationName))identification.name=this.stateListProfissionalDetailsIdentificationName as string;if(this.stateListProfissionalDetailsIdentificationStatus!==null)identification.status=this.stateListProfissionalDetailsIdentificationStatus;if(this.stateListProfissionalDetailsIdentificationDocType!==null)identification.docType=this.stateListProfissionalDetailsIdentificationDocType;if(this.has(this.stateListProfissionalDetailsIdentificationDocId))identification.docId=this.stateListProfissionalDetailsIdentificationDocId as string;if(this.has(this.stateListProfissionalDetailsIdentificationCountryCode))identification.countryCode=this.stateListProfissionalDetailsIdentificationCountryCode as string;if(Object.keys(identification).length)params.details={identification};if(this.stateListProfissionalPage!==null)params.page=this.stateListProfissionalPage;await this.query(K.profissionalStatus,'stateListProfissionalStatus',K.profissionalError,'stateListProfissionalError',K.profissionalResult,'stateListProfissionalResult',listProfissionalRoute,params);}
 private async query<T>(statusKey:string,statusMember:string,errorKey:string,errorMember:string,resultKey:string,resultMember:string,route:string,params:unknown):Promise<void>{this.publish(statusKey,statusMember,'loading');this.publish(errorKey,errorMember,null);try{const response=await this.call<T>(route,params,{mode:'silent'});if(response.ok&&response.data!==null){this.publish(resultKey,resultMember,response.data);this.publish(statusKey,statusMember,Array.isArray(response.data)&&response.data.length===0?'empty':'success');}else{const feedback=this.feedback(response.error,'Não foi possível carregar os dados.');this.publish(errorKey,errorMember,feedback);this.publish(statusKey,statusMember,'error');}}catch(error:unknown){this.publish(errorKey,errorMember,this.feedback(error,'Não foi possível carregar os dados.'));this.publish(statusKey,statusMember,'error');}}
 public enterBaseScenario():void{this.setScenario('base');} public enterDetailConsultaScenario():void{this.setScenario('detailConsulta');} public enterCreateConsultaScenario():void{this.setScenario('createConsulta');} public enterUpdateConsultaScenario():void{if(this.stateUpdateConsultaId===null){this.publish(K.updateError,'stateUpdateConsultaError',{code:'MISSING_REQUIRED_INPUT',message:'Selecione uma consulta antes de editar.'});return;}this.setScenario('updateConsulta');}

  /** setter for state ui.consultas.scenary */
  setUiScenary(value: string): void {
    const allowed: string[] = ['base', 'detailConsulta', 'createConsulta', 'updateConsulta'];
    if (!allowed.includes(value)) {
      console.warn('setUiScenary: unknown value \'' + value + '\'');
      return;
    }
    let next: string = value;
    if (value === 'updateConsulta' && (!this.id)) next = 'base';
    this.scenary = next as typeof this.scenary;
    setState('ui.consultas.scenary', next);
    this.syncScenaryQuery(next);
    this.requestUpdate();
  }

  /** handler for action set.uiScenary — bind UI events here */
  handleUiScenaryChange(event: Event): void {
    const custom = event as CustomEvent<{ value?: unknown }>;
    const fromDetail: string = custom.detail && typeof custom.detail.value === 'string' ? custom.detail.value : '';
    const target = event.target as HTMLInputElement | HTMLSelectElement | null;
    const value: string = fromDetail || (target && 'value' in target ? String(target.value) : '');
    this.setUiScenary(value);
  }

  private applyUrlScenary(): void {
    const params = new URLSearchParams(window.location.search);
    const rawId: string = params.get('id') || '';
    if (rawId) {
      if (!this.id) {
        this.id = rawId;
        setState('ui.consultas.updateConsulta.input.id', rawId);
      }
    }
    const requested: string = params.get('scenary') || 'base';
    this.setUiScenary(requested);
  }

  private syncScenaryQuery(value: string): void {
    const url = new URL(window.location.href);
    if (value === 'base') url.searchParams.delete('scenary');
    else url.searchParams.set('scenary', value);
    window.history.replaceState(window.history.state, '', `${url.pathname}${url.search}${url.hash}`);
  }

}
