/// <mls fileReference="_102047_/l2/layout/appHeaderHeader.ts" enhancement="_blank" />

// Project header generated by agentGenerateHeader (_102020_/l2/aura/agentManageHeader).
//
// The band, its fixed height, the brand, the mobile aside toggle and SPA navigation all come
// from AuraHeaderBase — this file only fills the band. The brand lives in the config profile
// (clientShell.regions.header.profiles[...].brand), so regenerating this file cannot lose it.

import { html } from 'lit';
import { AuraHeaderBase } from '/_102033_/l2/shared/layout/aura-header-base.js';

export class AppHeaderHeader102047 extends AuraHeaderBase {
  protected bandCss(): string {
    const tag = this.localName;
    return `
${tag} .app-header-left {
  gap: var(--space-16, 16px);
}

${tag} .app-header-right {
  gap: var(--space-16, 16px);
  color: var(--nav-text, #fff);
}

${tag} .app-header-right > * {
  color: var(--nav-text, #fff);
}

${tag} .app-header-right > *:hover {
  color: var(--nav-text-hover, #fff);
}

${tag} .app-header-right > *:focus-visible {
  color: var(--nav-text-focus, #fff);
  outline: 2px solid var(--nav-active-text, #fff);
  outline-offset: 2px;
}

${tag} .aura-header-brand {
  color: var(--nav-text, #fff);
}

${tag} .aura-header-title,
${tag} .aura-header-subtitle {
  color: var(--nav-text, #fff);
}
`;
  }

  protected renderBand() {
    return html`
      <div class="aura-header-side app-header-left">
        ${this.renderAsideToggle()}
        ${this.renderBrand()}
      </div>
      <div class="aura-header-side app-header-right">
        ${this.renderActions()}
        ${this.renderUserAvatar()}
      </div>
    `;
  }
}

customElements.define('layout--app-header-header-102047', AppHeaderHeader102047);
