/// <mls fileReference="_102047_/l2/agendaClinica/web/desktop/page11/consultas.ts" enhancement="_102020_/l2/enhancementAura"/>

import { html, nothing, type TemplateResult } from 'lit';
import { customElement } from 'lit/decorators.js';
import { ConsultasShared } from '/_102047_/l2/agendaClinica/web/shared/consultas.js';
import type { ListConsultaItem, ListPacienteItem, ListProfissionalItem } from '/_102047_/l2/agendaClinica/web/contracts/consultas.defs.js';
import '/_102020_/l2/molecules/ml-scenary.js';
import '/_102040_/l2/molecules/groupselectone/ml-select.js';
import '/_102040_/l2/molecules/groupenterdatetime/ml-datetime-picker.js';
import '/_102040_/l2/molecules/grouptriggeraction/ml-button-standard.js';
/// **collab_i18n_start**
const pageMessage_pt = {
agenda: 'Agenda clínica', consultations: 'Consultas', locate: 'Localize consultas e acompanhe os agendamentos da clínica.',
schedule: 'Agendar consulta', patient: 'Paciente', professional: 'Profissional', dateTime: 'Data e horário', status: 'Situação',
allPatients: 'Todos os pacientes', allProfessionals: 'Todos os profissionais', allStatuses: 'Todas as situações',
noPatients: 'Nenhum paciente disponível', noProfessionals: 'Nenhum profissional disponível', refine: 'Refine a agenda por data e horário.',
selectPatient: 'Selecione o paciente', selectProfessional: 'Selecione o profissional', chooseDate: 'Escolha quando a consulta será realizada.',
telephoneConfirmation: 'Confirmação telefônica', telephoneHelp: 'Informe quando a confirmação foi registrada.', loading: 'Carregando consultas…',
empty: 'Nenhuma consulta encontrada para os filtros informados.', selected: 'Consulta selecionada', close: 'Fechar', details: 'Detalhes',
unavailable: 'Não foi possível localizar a consulta selecionada.', actions: 'Ações da consulta', selectToAct: 'Selecione uma consulta para ver as ações disponíveis.',
confirmAction: 'Registrar confirmação telefônica', noShow: 'Registrar falta', update: 'Atualizar confirmação telefônica', cancel: 'Cancelar',
save: 'Salvar confirmação', newAppointment: 'Novo agendamento', updateTitle: 'Atualização', agendaTitle: 'Agenda',
scheduled: 'Agendada', noShowStatus: 'Falta registrada', attended: 'Atendida', notRecorded: 'Não registrada',
consultationOf: 'Consulta de', inAt: 'em', scheduledSuccess: 'Consulta agendada com sucesso.', confirmationSuccess: 'Confirmação telefônica registrada com sucesso.', noShowSuccess: 'Falta registrada com sucesso.',
};
type PageMessageType = typeof pageMessage_pt;
const pageMessage_en: PageMessageType = pageMessage_pt;
const pageMessages: Record<string, PageMessageType> = { pt: pageMessage_pt, en: pageMessage_en };
/// **collab_i18n_end**
const TAG = 'agenda-clinica--web--desktop--page11--consultas-102047';
type SelectChange = CustomEvent<{ value: string | null }>;
type DateChange = CustomEvent<{ value: string | null }>;
type ActionEvent = CustomEvent<Record<string, never>>;
@customElement('agenda-clinica--web--desktop--page11--consultas-102047')
export class ConsultasPage extends ConsultasShared {
private selectedConsultaId: string | null = null;
private readonly statusLabels: Record<ListConsultaItem['status'], string> = { scheduled: 'Agendada', noShow: 'Falta registrada', attended: 'Atendida' };
private msg<K extends keyof PageMessageType>(key: K): string {
const lang = (document.documentElement.lang || 'pt').toLowerCase().slice(0, 2);
return (pageMessages[lang] ?? pageMessage_pt)[key];
}
private formatDate(value: string): string { const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat('pt-BR', { dateStyle: 'short', timeStyle: 'short' }).format(date); }
private patientName(item: ListConsultaItem): string { return item.consultaPaciente?.details?.identification?.name ?? item.pacienteId; }
private professionalName(item: ListConsultaItem): string { return item.consultaProfissional?.details?.identification?.name ?? item.profissionalId; }
private selectedConsulta(): ListConsultaItem | undefined { return this.selectedConsultaId === null ? undefined : this.stateListConsultaResult.find((item: ListConsultaItem) => item.id === this.selectedConsultaId); }
private handleConsultaClick(item: ListConsultaItem): void { this.selectedConsultaId = item.id; this.selectRegistrarFaltaId(item.id); this.selectUpdateConsultaId(item.id); this.selectUpdateConsultaPacienteId(item.pacienteId); this.selectUpdateConsultaProfissionalId(item.profissionalId); this.setUpdateConsultaScheduledAt(item.scheduledAt); this.setUpdateConsultaDetailsTelephoneConfirmationConfirmedAt(item.details.telephoneConfirmation?.confirmedAt ?? null); this.enterDetailConsultaScenario(); }
private handlePatientFilter(event: SelectChange): void { this.selectListConsultaPacienteId(event.detail.value); void this.runListConsulta(); }
private handleProfessionalFilter(event: SelectChange): void { this.selectListConsultaProfissionalId(event.detail.value); void this.runListConsulta(); }
private handleDateFilter(event: DateChange): void { this.setListConsultaScheduledAt(event.detail.value); void this.runListConsulta(); }
private handleStatusFilter(event: SelectChange): void { const value = event.detail.value; if (value === 'scheduled' || value === 'noShow' || value === 'attended' || value === null) { this.setListConsultaStatus(value); void this.runListConsulta(); } }
private handleCreatePatient(event: SelectChange): void { this.selectCreateConsultaPacienteId(event.detail.value); }
private handleCreateProfessional(event: SelectChange): void { this.selectCreateConsultaProfissionalId(event.detail.value); }
private handleCreateDate(event: DateChange): void { this.setCreateConsultaScheduledAt(event.detail.value); }
private handleCreateConfirmation(event: DateChange): void { this.setCreateConsultaDetailsTelephoneConfirmationConfirmedAt(event.detail.value); }
private handleUpdateConfirmation(event: DateChange): void { this.setUpdateConsultaDetailsTelephoneConfirmationConfirmedAt(event.detail.value); }
private renderError(error: { message: string } | null): TemplateResult | typeof nothing { return error ? html`<p class="feedback feedback-error" role="alert">${error.message}</p>` : nothing; }
private renderPatientItems(): TemplateResult[] { return this.stateListPacienteResult.map((item: ListPacienteItem) => html`<Item value=${item.id}>${item.details.identification?.name ?? item.id}</Item>`); }
private renderProfessionalItems(): TemplateResult[] { return this.stateListProfissionalResult.map((item: ListProfissionalItem) => html`<Item value=${item.id}>${item.details.identification?.name ?? item.id}</Item>`); }
private renderList(): TemplateResult {
const filterStatus = this.stateListConsultaStatusX00007300007400006100007400006500003a00007500006900002e00006300006f00006e00007300007500006c00007400006100007300002e00006c00006900007300007400004300006f00006e00007300007500006c00007400006100002e00006900006e00007000007500007400002e000073000074000061000074000075000073;
const queryStatus = this.stateListConsultaStatusX00007300007400006100007400006500003a00007500006900002e00006300006f00006e00007300007500006c00007400006100007300002e00006c00006900007300007400004300006f00006e00007300007500006c00007400006100002e000073000074000061000074000075000073;
return html`<section class="list-organism" aria-labelledby="consultas-list-title"><div class="section-heading"><div><p class="eyebrow">${this.msg('agenda')}</p><h2 id="consultas-list-title">${this.msg('consultations')}</h2></div><grouptriggeraction--ml-button-standard @action=${(_event: ActionEvent) => this.enterCreateConsultaScenario()}><Label>${this.msg('schedule')}</Label></grouptriggeraction--ml-button-standard></div><div class="filters" aria-label="Filtros de consultas"><groupselectone--ml-select @change=${this.handlePatientFilter} .value=${this.stateListConsultaPacienteId}><Label>${this.msg('patient')}</Label><Trigger>${this.msg('allPatients')}</Trigger>${this.renderPatientItems()}<Empty>${this.msg('noPatients')}</Empty></groupselectone--ml-select><groupselectone--ml-select @change=${this.handleProfessionalFilter} .value=${this.stateListConsultaProfissionalId}><Label>${this.msg('professional')}</Label><Trigger>${this.msg('allProfessionals')}</Trigger>${this.renderProfessionalItems()}<Empty>${this.msg('noProfessionals')}</Empty></groupselectone--ml-select><groupenterdatetime--ml-datetime-picker @change=${this.handleDateFilter} .value=${this.stateListConsultaScheduledAt}><Label>${this.msg('dateTime')}</Label><Helper>${this.msg('refine')}</Helper></groupenterdatetime--ml-datetime-picker><groupselectone--ml-select @change=${this.handleStatusFilter} .value=${filterStatus}><Label>${this.msg('status')}</Label><Trigger>${this.msg('allStatuses')}</Trigger><Item value="scheduled">${this.msg('scheduled')}</Item><Item value="noShow">${this.msg('noShowStatus')}</Item><Item value="attended">${this.msg('attended')}</Item></groupselectone--ml-select></div>${queryStatus === 'loading' ? html`<p role="status">${this.msg('loading')}</p>` : nothing}${this.renderError(this.stateListConsultaError)}<div class="calendar" aria-label="Agenda de consultas"><div class="calendar-header"><span>${this.msg('dateTime')}</span><span>${this.msg('patient')}</span><span>${this.msg('professional')}</span><span>${this.msg('status')}</span></div>${this.stateListConsultaResult.map((item: ListConsultaItem) => html`<button class="calendar-row ${item.id === this.selectedConsultaId ? 'is-selected' : ''}" type="button" @click=${() => this.handleConsultaClick(item)}><span>${this.formatDate(item.scheduledAt)}</span><span>${this.patientName(item)}</span><span>${this.professionalName(item)}</span><span class="status status-${item.status}">${this.statusLabels[item.status]}</span></button>`)}${queryStatus !== 'loading' && this.stateListConsultaResult.length === 0 ? html`<p class="empty-state">${this.msg('empty')}</p>` : nothing}</div></section>`;
}
private renderDetail(): TemplateResult { const item = this.selectedConsulta(); return html`<section class="detail-panel" aria-labelledby="detail-title"><div class="section-heading"><h2 id="detail-title">${this.msg('selected')}</h2><button type="button" class="text-button" @click=${() => this.enterBaseScenario()}>${this.msg('close')}</button></div>${item ? html`<dl class="detail-grid"><dt>${this.msg('patient')}</dt><dd>${this.patientName(item)}</dd><dt>${this.msg('professional')}</dt><dd>${this.professionalName(item)}</dd><dt>${this.msg('dateTime')}</dt><dd>${this.formatDate(item.scheduledAt)}</dd><dt>${this.msg('status')}</dt><dd>${this.statusLabels[item.status]}</dd><dt>${this.msg('telephoneConfirmation')}</dt><dd>${item.details.telephoneConfirmation?.confirmedAt ? this.formatDate(item.details.telephoneConfirmation.confirmedAt) : this.msg('notRecorded')}</dd></dl>${this.renderError(this.stateUpdateConsultaError)}${this.renderError(this.stateUpdateConsultaResult ? null : null)}` : html`<p role="status">${this.msg('unavailable')}</p>`}</section>`; }
private renderForm(): TemplateResult { const update = this.scenary === 'updateConsulta'; return html`<section class="form-panel" aria-labelledby="form-title"><div class="section-heading"><h2 id="form-title">${update ? this.msg('update') : this.msg('newAppointment')}</h2><button type="button" class="text-button" @click=${() => this.enterBaseScenario()}>${this.msg('cancel')}</button></div><div class="form-grid"><groupselectone--ml-select required @change=${this.handleCreatePatient} .value=${update ? this.stateUpdateConsultaPacienteId : this.stateCreateConsultaPacienteId}><Label>${this.msg('patient')}</Label><Trigger>${this.msg('selectPatient')}</Trigger>${this.renderPatientItems()}<Empty>${this.msg('noPatients')}</Empty></groupselectone--ml-select><groupselectone--ml-select required @change=${this.handleCreateProfessional} .value=${update ? this.stateUpdateConsultaProfissionalId : this.stateCreateConsultaProfissionalId}><Label>${this.msg('professional')}</Label><Trigger>${this.msg('selectProfessional')}</Trigger>${this.renderProfessionalItems()}<Empty>${this.msg('noProfessionals')}</Empty></groupselectone--ml-select><groupenterdatetime--ml-datetime-picker required @change=${update ? this.handleCreateDate : this.handleCreateDate} .value=${update ? this.stateUpdateConsultaScheduledAt : this.stateCreateConsultaScheduledAt}><Label>${this.msg('dateTime')}</Label><Helper>${this.msg('chooseDate')}</Helper></groupenterdatetime--ml-datetime-picker><groupenterdatetime--ml-datetime-picker required @change=${update ? this.handleUpdateConfirmation : this.handleCreateConfirmation} .value=${update ? this.stateUpdateConsultaDetailsTelephoneConfirmationConfirmedAt : this.stateCreateConsultaDetailsTelephoneConfirmationConfirmedAt}><Label>${this.msg('telephoneConfirmation')}</Label><Helper>${this.msg('telephoneHelp')}</Helper></groupenterdatetime--ml-datetime-picker></div>${this.renderError(update ? this.stateUpdateConsultaError : this.stateCreateConsultaError)}${this.renderError(update ? null : this.stateCreateConsultaError)}${update && this.stateUpdateConsultaStatus === 'success' ? html`<p class="feedback feedback-success" role="status">${this.msg('confirmationSuccess')}</p>` : nothing}${!update && this.stateCreateConsultaStatus === 'success' ? html`<p class="feedback feedback-success" role="status">${this.msg('scheduledSuccess')}</p>` : nothing}<grouptriggeraction--ml-button-standard ?loading=${update ? this.stateUpdateConsultaStatus === 'loading' : this.stateCreateConsultaStatus === 'loading'} @action=${(_event: ActionEvent) => { if (update) void this.runUpdateConsulta(); else void this.runCreateConsulta(); }}><Label>${update ? this.msg('save') : this.msg('schedule')}</Label></grouptriggeraction--ml-button-standard></section>`; }
private renderActions(): TemplateResult { const item = this.selectedConsulta(); const canMarkNoShow = item?.status === 'scheduled'; return html`<section class="actions-panel" aria-labelledby="actions-title"><h2 id="actions-title">${this.msg('actions')}</h2>${item ? html`<p>${this.msg('consultationOf')} ${this.patientName(item)} ${this.msg('inAt')} ${this.formatDate(item.scheduledAt)}.</p><div class="action-row"><grouptriggeraction--ml-button-standard @action=${(_event: ActionEvent) => this.enterUpdateConsultaScenario()}><Label>${this.msg('confirmAction')}</Label></grouptriggeraction--ml-button-standard><grouptriggeraction--ml-button-standard data-variant="danger" ?disabled=${!canMarkNoShow || this.stateRegistrarFaltaStatus === 'loading'} ?loading=${this.stateRegistrarFaltaStatus === 'loading'} @action=${(_event: ActionEvent) => void this.runRegistrarFalta()}><Label>${this.msg('noShow')}</Label></grouptriggeraction--ml-button-standard></div>${this.renderError(this.stateRegistrarFaltaError)}${this.stateRegistrarFaltaStatus === 'success' ? html`<p class="feedback feedback-success" role="status">${this.msg('noShowSuccess')}</p>` : nothing}` : html`<p>${this.msg('selectToAct')}</p>`}</section>`; }
protected render(): TemplateResult { return html`<main class="consultas-page"><header class="page-header"><div><p class="eyebrow">${this.msg('agenda')}</p><h1>${this.msg('consultations')}</h1><p class="intro">${this.msg('locate')}</p></div></header><molecules--ml-scenary-102020 .value=${this.scenary} mode="direct" backLabel="Voltar" @change=${this.handleUiScenaryChange}><Scene value="base" title=${this.msg('agendaTitle')}><div class="scene-content">${this.renderList()}${this.renderActions()}</div></Scene><Scene value="detailConsulta" title=${this.msg('details')}><div class="scene-content">${this.renderDetail()}${this.renderActions()}</div></Scene><Scene value="createConsulta" title=${this.msg('newAppointment')}><div class="scene-content">${this.renderForm()}</div></Scene><Scene value="updateConsulta" title=${this.msg('updateTitle')}><div class="scene-content">${this.renderForm()}</div></Scene></molecules--ml-scenary-102020></main>`; }
}
