/// <mls fileReference="_102047_/l2/agendaClinica/web/mobile/page11/consultas.ts" enhancement="_102020_/l2/enhancementAura"/>

import { html, nothing, type TemplateResult } from 'lit';
import { customElement } from 'lit/decorators.js';
import { ConsultasShared } from '/_102047_/l2/agendaClinica/web/shared/consultas.js';
import '/_102020_/l2/molecules/ml-scenary.js';
import '/_102040_/l2/molecules/groupviewdata/ml-calendar-view.js';
import '/_102040_/l2/molecules/groupselectone/ml-select.js';
import '/_102040_/l2/molecules/groupenterdatetime/ml-datetime-picker.js';
import '/_102040_/l2/molecules/grouptriggeraction/ml-button-standard.js';
import '/_102040_/l2/molecules/grouptriggeraction/ml-button-group.js';
const SCENARY_TAG = 'molecules--ml-scenary-102020';
type ConsultaStatus = 'scheduled' | 'noShow' | 'attended';
type SceneName = 'base' | 'detailConsulta' | 'createConsulta' | 'updateConsulta';
type SelectorChange = { value: string | null };
type DatetimeChange = { value: string | null };
/// **collab_i18n_start**
const pageMessage_pt = {
title: 'Consultas', agenda: 'Agenda de consultas', details: 'Detalhes da consulta', create: 'Agendar consulta', update: 'Confirmação telefônica', noSelection: 'Nenhuma consulta selecionada.', noResults: 'Nenhuma consulta encontrada.', loading: 'Carregando consultas…', processing: 'Processando…', patient: 'Paciente', professional: 'Profissional', scheduledAt: 'Data e horário', status: 'Situação', confirmedAt: 'Confirmada em', actions: 'Ações da consulta', confirmPhone: 'Registrar confirmação telefônica', noShow: 'Registrar falta', select: 'Selecione', noOptions: 'Nenhuma opção disponível.', saveConfirmation: 'Salvar confirmação', appointmentScheduled: 'Consulta agendada.', confirmationSaved: 'Confirmação telefônica registrada.', noShowSaved: 'Falta registrada.',
};
type PageMessageType = typeof pageMessage_pt;
const pageMessage_en: PageMessageType = {
title: 'Consultations', agenda: 'Consultation schedule', details: 'Consultation details', create: 'Schedule consultation', update: 'Telephone confirmation', noSelection: 'No consultation selected.', noResults: 'No consultations found.', loading: 'Loading consultations…', processing: 'Processing…', patient: 'Patient', professional: 'Professional', scheduledAt: 'Date and time', status: 'Status', confirmedAt: 'Confirmed at', actions: 'Consultation actions', confirmPhone: 'Record telephone confirmation', noShow: 'Record no-show', select: 'Select', noOptions: 'No options available.', saveConfirmation: 'Save confirmation', appointmentScheduled: 'Consultation scheduled.', confirmationSaved: 'Telephone confirmation recorded.', noShowSaved: 'No-show recorded.',
};
const pageMessages: Record<string, PageMessageType> = { pt: pageMessage_pt, en: pageMessage_en };
/// **collab_i18n_end**
@customElement('agenda-clinica--web--mobile--page11--consultas-102047')
export class ConsultasPage11 extends ConsultasShared {
private statusLabel(status: ConsultaStatus): string { if (status === 'scheduled') return 'Agendada'; if (status === 'noShow') return 'Falta registrada'; return 'Atendida'; }
private formatDate(value: string): string { const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat('pt-BR', { dateStyle: 'short', timeStyle: 'short' }).format(date); }
private patientName(id: string): string { const patient = this.stateListPacienteResult.find((row) => row.id === id); return patient?.details.identification?.name ?? id; }
private professionalName(id: string): string { const professional = this.stateListProfissionalResult.find((row) => row.id === id); return professional?.details.identification?.name ?? id; }
private msg(key: keyof PageMessageType): string { const lang = (document.documentElement.lang || 'pt').toLowerCase().slice(0, 2); return (pageMessages[lang] ?? pageMessage_pt)[key]; }
private handlePatientChange(event: Event, update: boolean = false): void { const detail = (event as CustomEvent<SelectorChange>).detail; const value = detail?.value ?? null; if (update) this.selectUpdateConsultaPacienteId(value); else this.selectCreateConsultaPacienteId(value); }
private handleProfessionalChange(event: Event, update: boolean = false): void { const detail = (event as CustomEvent<SelectorChange>).detail; const value = detail?.value ?? null; if (update) this.selectUpdateConsultaProfissionalId(value); else this.selectCreateConsultaProfissionalId(value); }
private handleDateChange(event: Event, update: boolean = false): void { const detail = (event as CustomEvent<DatetimeChange>).detail; const value = detail?.value ?? null; if (update) this.setUpdateConsultaScheduledAt(value); else this.setCreateConsultaScheduledAt(value); }
private handleTelephoneChange(event: Event, update: boolean = false): void { const detail = (event as CustomEvent<DatetimeChange>).detail; const value = detail?.value ?? null; if (update) this.setUpdateConsultaDetailsTelephoneConfirmationConfirmedAt(value); else this.setCreateConsultaDetailsTelephoneConfirmationConfirmedAt(value); }
private selectConsulta(event: Event): void { const index = (event as CustomEvent<{ index?: number }>).detail?.index; if (typeof index !== 'number') return; const consulta = this.stateListConsultaResult[index]; if (!consulta) return; this.selectRegistrarFaltaId(consulta.id); this.selectUpdateConsultaId(consulta.id); this.enterDetailConsultaScenario(); }
private renderSelector(label: string, value: string | null, rows: Array<{ id: string; label: string }>, change: (event: Event) => void, name: string): TemplateResult { return html`<groupselectone--ml-select .value=${value} name=${name} required @change=${change}><Label>${label}</Label><Trigger>${value ? rows.find((row) => row.id === value)?.label ?? value : `${this.msg('select')} ${label.toLowerCase()}`}</Trigger>${rows.map((row) => html`<Item value=${row.id}>${row.label}</Item>`)}${rows.length === 0 ? html`<Empty>${this.msg('noOptions')}</Empty>` : nothing}</groupselectone--ml-select>`; }
private renderCalendar(): TemplateResult { const loading = this.pageStatus === 'loading'; const error = this.stateListConsultaError?.message; return html`<section class="consultas-calendar" aria-labelledby="consultas-calendar-title"><h2 id="consultas-calendar-title">${this.msg('agenda')}</h2>${error ? html`<p role="alert">${error}</p>` : nothing}<groupviewdata--ml-calendar-view .loading=${loading} @row-click=${(event: Event) => this.selectConsulta(event)}><Columns><Column field="scheduledAt" header=${this.msg('scheduledAt')}></Column><Column field="patient" header=${this.msg('patient')}></Column><Column field="professional" header=${this.msg('professional')}></Column><Column field="status" header=${this.msg('status')}></Column></Columns><Rows>${this.stateListConsultaResult.map((consulta) => html`<Row><Cell>${this.formatDate(consulta.scheduledAt)}</Cell><Cell>${this.patientName(consulta.pacienteId)}</Cell><Cell>${this.professionalName(consulta.profissionalId)}</Cell><Cell>${this.statusLabel(consulta.status)}</Cell></Row>`)}</Rows>${!loading && this.stateListConsultaResult.length === 0 ? html`<Empty><p>${this.msg('noResults')}</p></Empty>` : nothing}${loading ? html`<Loading><p aria-live="polite">${this.msg('loading')}</p></Loading>` : nothing}</groupviewdata--ml-calendar-view></section>`; }
private renderForm(update: boolean): TemplateResult { const patientValue = update ? this.stateUpdateConsultaPacienteId : this.stateCreateConsultaPacienteId; const professionalValue = update ? this.stateUpdateConsultaProfissionalId : this.stateCreateConsultaProfissionalId; const dateValue = update ? this.stateUpdateConsultaScheduledAt : this.stateCreateConsultaScheduledAt; const telephoneValue = update ? this.stateUpdateConsultaDetailsTelephoneConfirmationConfirmedAt : this.stateCreateConsultaDetailsTelephoneConfirmationConfirmedAt; const status = update ? this.stateUpdateConsultaStatus : this.stateCreateConsultaStatus; const error = update ? this.stateUpdateConsultaError : this.stateCreateConsultaError; const patients = this.stateListPacienteResult.map((row) => ({ id: row.id, label: row.details.identification?.name ?? row.id })); const professionals = this.stateListProfissionalResult.map((row) => ({ id: row.id, label: row.details.identification?.name ?? row.id })); const result = update ? this.stateUpdateConsultaResult : this.stateCreateConsultaResult; return html`<section class="consultas-form" aria-labelledby="consultas-form-title"><h2 id="consultas-form-title">${update ? this.msg('update') : this.msg('create')}</h2>${status === 'loading' ? html`<p role="status" aria-live="polite">${this.msg('processing')}</p>` : nothing}${error ? html`<p role="alert">${error.message}</p>` : nothing}${result ? html`<p role="status" aria-live="polite">${update ? this.msg('confirmationSaved') : this.msg('appointmentScheduled')}</p>` : nothing}${this.renderSelector(this.msg('patient'), patientValue, patients, (event: Event) => this.handlePatientChange(event, update), update ? 'update-paciente' : 'create-paciente')}${this.renderSelector(this.msg('professional'), professionalValue, professionals, (event: Event) => this.handleProfessionalChange(event, update), update ? 'update-profissional' : 'create-profissional')}<groupenterdatetime--ml-datetime-picker .value=${dateValue} locale="pt-BR" required @change=${(event: Event) => this.handleDateChange(event, update)}><Label>${this.msg('scheduledAt')}</Label></groupenterdatetime--ml-datetime-picker><groupenterdatetime--ml-datetime-picker .value=${telephoneValue} locale="pt-BR" required @change=${(event: Event) => this.handleTelephoneChange(event, update)}><Label>${this.msg('confirmedAt')}</Label></groupenterdatetime--ml-datetime-picker><grouptriggeraction--ml-button-standard ?loading=${status === 'loading'} @action=${() => update ? void this.runUpdateConsulta() : void this.runCreateConsulta()}><Label>${update ? this.msg('saveConfirmation') : this.msg('create')}</Label></grouptriggeraction--ml-button-standard></section>`; }
private renderDetail(): TemplateResult { const consulta = this.stateListConsultaResult.find((row) => row.id === this.stateRegistrarFaltaId) ?? this.stateListConsultaResult[0]; if (!consulta) return html`<section aria-labelledby="consulta-detail-title"><h2 id="consulta-detail-title">${this.msg('details')}</h2><p>${this.msg('noSelection')}</p></section>`; const confirmedAt = consulta.details.telephoneConfirmation?.confirmedAt; return html`<section class="consultas-detail" aria-labelledby="consulta-detail-title"><h2 id="consulta-detail-title">${this.msg('details')}</h2><dl><dt>${this.msg('patient')}</dt><dd>${this.patientName(consulta.pacienteId)}</dd><dt>${this.msg('professional')}</dt><dd>${this.professionalName(consulta.profissionalId)}</dd><dt>${this.msg('scheduledAt')}</dt><dd>${this.formatDate(consulta.scheduledAt)}</dd><dt>${this.msg('status')}</dt><dd>${this.statusLabel(consulta.status)}</dd>${confirmedAt ? html`<dt>${this.msg('confirmedAt')}</dt><dd>${this.formatDate(confirmedAt)}</dd>` : nothing}</dl></section>`; }
private renderActions(): TemplateResult { const consulta = this.stateListConsultaResult.find((row) => row.id === this.stateRegistrarFaltaId); const eligible = consulta?.status === 'scheduled'; const status = this.stateRegistrarFaltaStatus; const result = this.stateRegistrarFaltaResult; return html`<section class="consultas-actions" aria-labelledby="consultas-actions-title"><h2 id="consultas-actions-title">${this.msg('actions')}</h2>${this.stateRegistrarFaltaError ? html`<p role="alert">${this.stateRegistrarFaltaError.message}</p>` : nothing}${result ? html`<p role="status" aria-live="polite">${this.msg('noShowSaved')}</p>` : nothing}<grouptriggeraction--ml-button-group><grouptriggeraction--ml-button-standard @action=${() => this.enterUpdateConsultaScenario()}><Label>${this.msg('confirmPhone')}</Label></grouptriggeraction--ml-button-standard><grouptriggeraction--ml-button-standard data-variant="danger" .disabled=${!eligible || status === 'loading'} ?loading=${status === 'loading'} @action=${() => void this.runRegistrarFalta(true)}><Label>${this.msg('noShow')}</Label></grouptriggeraction--ml-button-standard></grouptriggeraction--ml-button-group></section>`; }
render(): TemplateResult { const active = this.scenary; return html`<main class="consultas-page" aria-labelledby="consultas-title"><header><h1 id="consultas-title">${this.msg('title')}</h1><grouptriggeraction--ml-button-standard @action=${() => this.enterCreateConsultaScenario()}><Label>${this.msg('create')}</Label></grouptriggeraction--ml-button-standard></header><molecules--ml-scenary-102020 .value=${active} mode="scenary" @change=${this.handleUiScenaryChange}><Scene value="base" title=${this.msg('agenda')}>${this.renderCalendar()}</Scene><Scene value="detailConsulta" title=${this.msg('details')}>${this.renderDetail()}${this.renderActions()}</Scene><Scene value="createConsulta" title=${this.msg('create')}>${this.renderForm(false)}</Scene><Scene value="updateConsulta" title=${this.msg('update')}>${this.renderForm(true)}</Scene></molecules--ml-scenary-102020></main>`; }
}
